### ISSUE TITLE
Head Glitches Through The Car

### ISSUE THREAD

**Issue by EpiKDeadman** [LukeRoss00/gta5-real-mod#118]
So I use a modpack of over 1430 cars. Yes that is a lot but I have variety, I have many other mods installed as well to make the game as close to real life as possible. So when I hop into my Honda Civic Sedan 2016, my head glitches through the roof and doors (Only with the doors if I look at it to my left).

I also have another problem where, when I move my character with my mouse the game doesn’t have a “motion blur” you can call it. I’m not entire sure how else to describe it, but when I move my body with my head, or a car drives past me while I’m in my car, or when I turn in a car. It has a “motion blur” effect and I have motion blur off. This also happens when I go into third-person or when I buy a weapon, but instead everything is blurry apart from the HUD, or the character I’m playing as. Any fixes?

**Comment by LukeRoss00** [comment]
Are you using Redux together with my mod?

**Comment by EpiKDeadman** [comment]
> Are you using Redux together with my mod?

No, I don't use Redux although I do use VisualV, NaturalVision, L.A Roads, 4K Blood, Dirt and Water etc.

**Comment by LukeRoss00** [comment]
Your head appearing to clip through the roof and/or left window of some vehicles is unfortunately normal; it depends on the default position that the game chooses for the 1st person camera, which for many vehicles is not even aligned with your in-game character's head. You can work around this issue by recentering while craning your neck up and to the left, so when you relax your point of view will reach the desired position.

I find it hard to understand what you mean by motion blur. It could be just the effect of alternate eye rendering: to test that, press `F11` and then `NUMPAD2` to switch to monoscopic rendering. If you still have motion blur in mono mode, then it's caused by some of the other mods that you're using.
