### ISSUE TITLE
WMR Support

### ISSUE THREAD

**Issue by Trickypreece** [LukeRoss00/gta5-real-mod#126]
I was using you mod on quest before I sold it and it worked beautifully. Do you think you will solve the issues with WMR Headsets or should i consider getting a Rift s?

**Comment by LukeRoss00** [comment]
I cannot solve the issues with WMR myself: the problem lies within the Microsoft driver, and they said it also requires some contribution by Valve.

Getting a Rift S only for my mod seems a little extreme (!), but to be honest the chances that WMR will ever fix alternate eye rendering seem pretty slim.

**Comment by Trickypreece** [comment]
Thankyou so much for the fast reply and well done on this MOD..... Il ponder getting a rift s lol :)
