### ISSUE TITLE
Roll and Pitch Stability 

### ISSUE THREAD

**Issue by jdawgzim** [LukeRoss00/gta5-real-mod#129]
First: This mod is amazing and I can't thank you enough for all the work you've put into this mod.

Request: I know this might be difficult to implement (maybe impossible) but can we get Roll and Pitch stability in vehicles?  **Rotation** is the number one way to make someone sick in VR.

Examples:
In Dirt Rally 2.0 most people don't get sick because it keeps your eyes/head stability parallel with the ground.  Yaw is the only rotation that locks with the car.  That is until the car crashes and rotation goes too far so it's gotta pull you along flipping forward (pitch) and sideways (roll).  

Real driving in real life also has this as our eyes and head naturally try to stabilize our vision.  Try bouncing in your chair right now or tilting your head and you see that your brain and eyes try to stabilize your view.  

I know this might be really hard to implement but it's also a super cause for nausea in this game.  It also causes more noticeable double vision and blur when things rotate.  Doing that mission where you first ride bikes that tilt (roll) and then riding waverunners that bounce your view (pitch) was insanely nauseating!  Yet, I could imagine doing these activities and having a lot of fun with some added rotation stability.

Thanks for reading this.  I'm playing with your mod with a G29 steering wheel and the experience is near perfect!  So so much fun!

**Comment by LukeRoss00** [comment]
Happy that you're enjoying the mod!!

I won't be implementing the feature you request (but read on: there is a trick to achieve it anyway) for various reasons:
_a._ I'm quite busy with other, work-related projects at the moment, so Release 4 of the mod will probably be the last, at least for several months of the foreseeable future;
_b._ a vast majority of users, myself included, prefer the current implementation which follows directly how the GTA V gameplay camera behaves normally;
_c._ having your point of view glide steadycam-like while your vehicle (and your character's body!) tilts and rolls wildly around you looks quite ridiculous and immersion-breaking;
_d._ I'm completely immune to simulator sickness at this point so I can't judge, but studies show that having a visual frame of reference (the vehicle in our case) which is _attached to your point of view_ is the best way to reduce motion sickness;
_e._ as you said, the horizon artificial stabilization would have to be disabled after the vehicle rolls past a certain angle, with an even more jarring effect, and
_f._ it works horribly with airplanes.

That said, if you really want to try it for yourself, my friend [/u/iupvoteevery](https://www.reddit.com/user/iupvoteevery) discovered some time ago that you can exploit a game bug to obtain the effect you seek. Turn _on_ `Settings> Camera>  Allow Independent Camera Modes`, which I normally recommend people set to Off exactly because of this bug. Then, when you're playing, make sure that the camera is in third person just before you enter a vehicle. To be clear: you can still play the whole game in first person, and should definitely use first person for driving, but switch to third while you're still on foot just before entering vehicles. This will trigger a game bug where the camera moves to your head position inside the vehicle, instead of hovering a few feet above the vehicle roof, but (this is the crucial part) it keeps the steadycam behavior of third person.

**Comment by jdawgzim** [comment]
Yea, it would probably not work well in planes.  Both Project Cars 2 and Dirt Rally 2.0 are using it so it works amazing in cars to make the driving more enjoyable.  
Thanks for the response!  I'll try the glitch you recommend.  Maybe I could try to work it into a separate mod.

**Comment by LukeRoss00** [comment]
> I'll try the glitch you recommend.

Let us know whether it's the behavior you wanted and it helps you. But no, I certainly _don't_ recommend it. My recommendation is to have Allow Independent Camera Modes set to Off.
