### ISSUE TITLE
SLI issue and minor bug reporting

### ISSUE THREAD

**Issue by Aikimaniak** [LukeRoss00/gta5-real-mod#171]
Hello Luke,

Really into your mod recently due to its greatness and also quarantine...

So I was trying to make it looks even greater and found out some minor bugs that I would like to share with you.

When using SLI, (tested with 2 way SLI Titan X Pascal) the right eye is blind, it is completely dark, the game doesn’t display in right eye but you still can see the radar (when it’s on, of course), so I guess the game layer is off but the HUD layer is still on.
Anyhow SLI often makes things messy when it comes to VR!!! I faced numerous issues with games which got messy as soon as SLI was on so it may have no issue with the mod itself. But anyway just so you know...

When trying to set a higher resolution (ie 2048x2048 in the settings.xml and commandline.txt) the HUD containing the radar gets distorted, narrowed, that has an effect: during cut scenes there is 2 black lines appearing on both left and right sides in the middle the FOV. The greater you try to increase the resolution the more the lines get big, becoming more than lines and turning into black strips.
My only way to fix that, was to set it back to 1080x1080 which seems to be the only tolerated thus perfect setting...

When trying to play with the settings.xml and commandline.txt files I tried to push the frame rate a little higher first 90 then 120 (default was 60)...
120 made the game crash... maybe this has nothing to do with the game nor the mod it may have something to do with my rig itself not powerfull enough to handle it... don’t really know but just to let you know.

Really looking forward to improve the experience... but don’t take me wrong the experience is already WONDERFUL!!!!

Huge fan of yours
Cheers from France

**Comment by LukeRoss00** [comment]
Hi! Really dig your enthusiasm for the mod :-)

SLI: nope, sorry. The situation with SLI and VR is basically that they don't mix. NVIDIA came out with a solution that saw almost no adoption (so they will probably drop support for it sooner or later, just like they did with 3D Vision), and neither Oculus nor SteamVR support SLI officially. Besides, in this case the situation is especially complex due to the fact that GTA V takes advantage of SLI, but in 2D mode (specifically with AFR) whereas NVIDIA's VR SLI needs a different approach. So, considering all the technical issues and the fact that so few people use a SLI configuration these days, I'm not going to invest any time in that.

Resolution: using such a high base window resolution (2048x2048) makes no sense with current hardware. You're basically killing your performance to obtain a 5120x5120 render target that will need to be heavily downsampled before being displayed in the headset. Please read my hints at https://github.com/LukeRoss00/gta5-real-mod#even-more-advanced-resolution-tweaking. Much better results can be had by enabling MSAA 2x + TXAA (https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking)

Frame rate: you cannot control frame rate changing `<RefreshRate value="60" />`. That value is only meaningful in 2D when VSync is turned on: it has no impact on the headset frame rate.
