### ISSUE TITLE
I would lkle to play online

### ISSUE THREAD

**Issue by benjoeben117** [LukeRoss00/gta5-real-mod#176]
If this question it's in the wrong place I'm really sorry. I recently got the game and set the mod up, the game play was awesome and I'm excited to play the story mode in VR. However, I really like online game play. When getting my pc I was excited in general to be able to play GTA V on my computer. Now that the mod it in place and working, I can't join online because its not a genuine copy anymore. Is there an easy way to revert the game back to play online then to play Story mode turn the mod back on. Or even better, is there a way to get this mod to work online? Thank you so much for taking the time to read this message, again I'm really sorry if the question is posted in the wrong place. Thanks again.

**Comment by LukeRoss00** [comment]
No worries, this is indeed the right place to ask! Unfortunately it is impossible to play online with this or any other mods, as Rockstar would ban your account (which is why Script Hook V, which is a necessary component of my mod, won't even let you go online).

For the same reason, since the Rockstar launcher will actively inspect your game folder looking for extraneous files, it's not possible to just "disable" the mod but you have to actually remove it if you want to play online. See #63 for some helpful batch files to do that.

**Comment by benjoeben117** [comment]
Awesome!!! Thank you so much for your help. I think I found a work around lol. I had originally paid $30 on steam to get the game. I was very sad to see Epic Games offer it for free. But after thinking about it, I though hey, why not keep steam GTA V for vr and download Epic Games and the free GTA V and use that version for ligit play. Lol

Thank you again so much for your reply to this inquiry, I really appreciate  it.

I also want to say AMAZING job on the work you did for that mod, it is absolutely amazing!! Even having to play it on med graphics,  lost a little detail in the game play but it runs very smooth.
