### ISSUE TITLE
Jerky movement

### ISSUE THREAD

**Issue by deeproy84** [LukeRoss00/gta5-real-mod#188]
The camera is very jerky when turning my head, standing still and even rotating the camera with the controller is smooth. The game is on high settings and looks amazing other than that. I have ASW mode turned off, and Motion smoothing in Steam VR... any ideas?

**Comment by deeproy84** [comment]
Also, when on the pause menu, looking around with the headset is very smooth

**Comment by cmcosta81** [comment]
This is the part of  same issue as https://github.com/LukeRoss00/gta5-real-mod/issues/184

**Comment by LukeRoss00** [comment]
@deeproy84 Which headset?

**Comment by BenCearlock** [comment]
@LukeRoss00 I'm seeing the same jitter issue as above when using the recently-modified-but-unofficial scripthookv. If I can keep my head still, everything is fine. When I move my head, the screen jitters until I I stop again.  Also, as above, when I pause, the motion behind the menu appears smooth (though, I don't think it's rendering the same scene while paused, so that may not be related). 

I'm using an Oculus Quest through Virtual Desktop.

**Comment by KptnKMan** [comment]
@BenCearlock Please see issue #145 
Its an ongoing issue that renders this mod unusable when using Virtual Desktop.
The recommended solution is to use Oculus Link. 👍

**Comment by sheepdestroyer** [comment]
Seeing this on Valve Index

**Comment by LukeRoss00** [comment]
@sheepdestroyer Please check that motion smoothing is off (it's incompatible with AER). Are you sure that you're actually achieving 120 fps? Please check with the mod's internal frame rate counter (`F11` and then `N` will turn it on in the lower right corner of the HUD). To get stable 120 fps you need a beefy GPU, at least a 1080 Ti, and Low/Medium settings. On High settings even powerful cards cannot maintain 120 fps in all game areas.

**Comment by sheepdestroyer** [comment]
I checked that motion smoothing is off
I am sure that I am stable at 90 and 120 fps, checked with both internal frame counter and fpsVR
There is no ghosting effect at all if I disable stereo rendering : F11 - 2
There is strong Ghosting at both 90fps and 120fps with stereo rendering on. Even when closing one eye.

**Comment by LukeRoss00** [comment]
Okay, then it's positive that what you're seeing is simply the stroboscopic doubling associated with alternate eye rendering. 120 fps will not make it less visible if you really go looking for it, but it should definitely make it less annoying because the two images will be closer together due to the shorter frame time, which means shorter traveled distances.

In the end what matters, just like with the screen door effect or the washed out LCD colors, is whether or not you can persuade your brain to just live with it and ignore it!
