### ISSUE TITLE
GTA V 3d

### ISSUE THREAD

**Issue by coru182** [LukeRoss00/gta5-real-mod#193]
Hey Luke,

i saw in your post that you are trying to figure out how to render 2 frames at the same time. Have you looked at this? https://thebergerbits.com/?p=1249 
I noticed in the settings.xml file these 3 settings 

<Stereo value="0" />
    <Convergence value="0.950000" />
    <Separation value="31.999695" />

and upon googling, came to the link above.
Just wanted to share with you, in case that helps you in any way.

Thanks for your hard work on this. 
I have been enjoying this mod a lot!

**Comment by LukeRoss00** [comment]
Thanks for the appreciation!

Unfortunately, very early in development, I had to discard the 3D Vision approach, which doesn't work for many reasons:
1. it requires an NVIDIA card;
2. even with the right hardware, NVIDIA has long discontinued 3D Vision technology, so users would be forced to jump through hoops in order to either install outdated drivers or hack recent ones;
3. GTA V is one of those games where performance in 3D Vision mode has historically been abysmal (depending on the system configuration, we're talking about 1/3 of the frame rate that you get in 2D);
4. the stereo projection needed for VR is different from the one that works on a 3D screen, so the virtual world reconstruction would be slight off;
5. GTA V only allows stereo mode when in fullscreen, which brings about a slew of other problems related to resolution, wasted pixels and forced V-Sync.

So in the end, for these and other, more complex technical reasons, the R.E.A.L. mod cannot use the native stereo rendering capabilities built into GTA V.

**Comment by coru182** [comment]
Thanks for taking the time to throughly answer.

Take care man.
