### ISSUE TITLE
Duplicated/misaligned crosshair when using WMR

### ISSUE THREAD

**Issue by coru182** [LukeRoss00/gta5-real-mod#212]
Hello, i noticed the crosshair is duplicated when playing in WMR (in monoscopic mode).
I see 2 dots for the crosshair, although the one displayed on my right eye, is the one where shots land.

I tried using the hotkeys to change the dominant eye, but that doesn't seem to change anything. 
Aiming down sights works perfectly tho, its when firing from the hip or without ADS that the crosshair is doubled.

Thanks

**Comment by LukeRoss00** [comment]
I'm sorry but I cannot reproduce the issue here. On my CV1, the crosshair dot looks fine (at the correct depth and not doubled) both in stereo 3D and mono mode.

Are the two dots that you see clearly separated? For instance, if you stand about 2 meters from a wall and aim at it, how far apart would you say that the two dots appear on the wall?

**Comment by coru182** [comment]
Yeah,  they are clearly separated. I actually was mistaken before. Looks like my left eye is the dominant eye, cause that's where shot lands. I took a screenshot and edited to show you where the doubled crosshair is. (the one my right eye sees)
![GTA5_2020_07_02_08_50_43_099](https://user-images.githubusercontent.com/62523397/86355795-9e1fc600-bc41-11ea-9d9b-40a5c4035274.png)
You'll see the bullet hole, which is where my left eye sees the crosshair and in red, the one my right eye sees. 
That causes the crosshair to look duplicated/missaligned when looking with both eyes.

**Comment by ODEH67** [comment]
Hi , maybe my comment have nothing to do with is thread but I had to say, @LukeRoss00  I just saw the new release of your MOD for WMR, an awesome job as always 👍 ,, It is awesome how Microsoft quickly responded to this issue , sorry that I wasn't following by since we discussed this issue from the beginning , there was a lot going on ... since I caused this issue I should try it from every angle with my Reverb and give u my feedback. that is least I can do..
@coru182 thanks for responding and helping with issue and sorry for the late responses 😅
btw I pre-ordered the Reverb G2 😂

**Comment by LukeRoss00** [comment]
@ODEH67 Thank you, looking forward to you sharing your experience!
