### ISSUE TITLE
Oculus Rift CV1 Stutter/Performance issue

### ISSUE THREAD

**Issue by Outlaw313** [LukeRoss00/gta5-real-mod#214]
Yello,

Hope all is well, I'm reaching out to see if I could get a bit of help with my GTA REAL mod. I get some pretty nasty stutters when I'm in stereo 3d mode on my CV1 across all graphic presets in the RealConfig.bat file. Below I've taken a clip of what I'm seeing using Oculus mirror, and you'll notice when the fps counter reads "A" in stereo mode there are some hard stutters and when it's disabled the counter reads "M" (I know you know what those mean, it just makes me feel reassured stating those here lol) and the games runs like a proper VR title would although the counter reads a locked 38 fps. The game ran smoothly once before, after I relaunched the game but upon loading into single player it was as if the game ALT+Tabbed itself out and there was no sound after that happened (default sound device set to Rift Audio), but the game ran smoothly like a VR title with 3d in the headset. Every time after that it ran with sound but the stuttering returned. I'm running on a clean install and also attached a screenshot of my install folder. Async is also disabled. Thanks a bunch in advance for your time! 

![explorer_h9oFYnqE2O](https://user-images.githubusercontent.com/67928404/86646175-09a0c500-bfad-11ea-92fb-89e10587c131.png)

Here's a link to the clip mentioned above (I've taken the sound out so no worries about blaring volumes)
https://www.youtube.com/watch?v=uqKkxBi3Ju0

My specs:
i7 4790K
Nvidia GTX 1080
16 gigs of Ram
Win 10 Pro (Latest updates)
Geforce Game Ready Driver: 451.48

**Comment by LukeRoss00** [comment]
The stutters are due to the low frame rate. I don't understand why your game should be locked at 38 fps, though. With the CV1 it would make sense if it locked at 45 fps at worst, and then only with ASW enabled (which I don't recommend). With ASW disabled, as you correctly showed in the video, the frame rate should be free to reach 90.

Depending on the graphics settings, it might be that your computer struggles to maintain 90 fps everywhere. But what should happen in that case is the frame rate going up and down according to what you're doing in game. I've never seen a constant 38.

The audio might be a clue. Try again Alt-Tabbing out of the game, which will make GTA V suspend sound output, and see whether that changes the frame rate.

**Comment by Outlaw313** [comment]
I appreciate your reply, I've just went and reinstalled the game for a clean slate and reinstalled the mod but ended up with the same results 😅. I tried alt tabbing out and it was still giving me a locked 38fps. Even tried working some magic in the Nvidia control panel but no luck.

**Comment by LukeRoss00** [comment]
It's almost certainly something else in the system (not the game or the mod) that's causing the issue, but let's see if there's anything wrong that comes up in the log.

Edit the `RealVR.ini` file with Notepad and add a line `RVRLog = 1` at the end. Then run the game for a couple of minutes (loading + 1 minute gameplay) and quit. You will find an `RVRLog.txt` file in the game directory, please zip it and attach it here.

**Comment by Outlaw313** [comment]
That's a bummer, but would make sense. Here's the log.

[Outlaw313's RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4887022/Outlaw313.s.RVRLog.zip)

**Comment by LukeRoss00** [comment]
So, from the log I can see a few things.

First, for some reason you're not using the latest release of my mod, you nasty ;-) That shouldn't make a big difference, but it's probably best if you update so that we're on the same page.

But more importantly, your system is spending an inordinate amount of time (up to 30 ms per frame) in the Present() call, which should be almost instantaneous. That tells me that either you have V-Sync forced On in the NVIDIA driver, which is a BAD thing to do, or—perhaps more likely—you have some "helpful" bloatware overlay that is forcing itself in the rendering loop and squandering your frame time to do God knows what.

Could you check and report back what you find?

**Comment by Outlaw313** [comment]
Sooo I definitely made a silly mistake here. I went and got the updated version of the mod, but when you mentioned the "helpful" overlay I closed out MSI afterburner and Rivera and everything worked like a charm. Then it hit me that I had a hard 38 fps limit set in Rivera from when I last played gta over a year ago that completely left my mind 😅. I had set it in conjunction with using NaturalVision and other mods while plugged into the tv for a next level movie like feel. I saw your mod on VR Oasis's channel and it was a big driver behind picking up a headset. Thanks a ton for your help! It's definitely very much appreciated and my apologies for the hiccup there.

**Comment by Outlaw313** [comment]
Btw is there any way I could show support for your work?

**Comment by LukeRoss00** [comment]
> my apologies for the hiccup there

Hey, no problem man, I'm just glad that we could sort it out in the end!

> is there any way I could give support

I'm not considering donations for now, just spread the word so people like us who enjoy GTA V and all it has to offer can experience it properly in VR!

**Comment by Outlaw313** [comment]
Most definitely will do 💪🏽 and thanks again! This is an absolutely mind blowing experience!!
