### ISSUE TITLE
Release 5.0 for WMR, OpenXR

### ISSUE THREAD

**Issue by ODEH67** [LukeRoss00/gta5-real-mod#220]
Hi there, as I said I wanted to go through this new release for WMR to cover every issue that we could come across while installing, activating and using the Mod ... 

**My Setup:**

**-GTA V steam version , (trying the Epic games version soon)**

**-Windows 10 pro**

**-MB: Asus TUF GAMING X570-PLUS,**

**-AMD Ryzen 5 3600 WATER COOLED,**

**-(2 x 8 GB) DDR4-3200,**

**-Asus RTX 2080 super OC 8G extreme**

**- Headset: HP Reverb pro**

so as a start the first problem I have is activating or setup the openxr in the Windows mixed reality portal, after following all steps in the mod description :

- windows updated to latest **version 1909**, (recommended 1903 and above)
- new mod 5.0 files been installed and replaced in the Game folder
-  **VRAPI = 0** changed to **VRAPI = 3**  in **RealVR.ini** file using notepad
- Windows Settings> Mixed Reality> Experience Options set to Best visual quality since my PC is capable for it 👇
https://www.reddit.com/r/WindowsMR/comments/hndp20/tips_to_getting_real_vr_mod_for_grand_theft_auto/

and here still the main problem, the most important step **"setup Openxr"** seems does not appear at all ,,, i even tried the delevoper mode. nothing..👇
![Screenshot (47)](https://user-images.githubusercontent.com/63449828/87226599-2f571100-c395-11ea-864b-5b415bb51231.png)

btw the **WMR portal** is already installed way before releasing this new **openxr** thing

the only way that still works with no juddering is by pressing **Numpad 2** for stereo rendering which make the game looks a 2D on a flat screen,,,

why is **"setup openxr"** does not appear? maybe because its already automatically installed or activated , but this will be against what been described in the microsoft website which is still soon to be done automatically ,,, 👇
https://docs.microsoft.com/en-us/windows/mixed-reality/openxr-getting-started#getting-started-with-openxr-for-windows-mixed-reality-headsets
or because in my opinion its not installed at all and thats why changing the **"VRAPI = 0    to VRAPI = 3    in RealVR.ini"** does not do any change in order to make the mod render using the **OpenXR** (which is not there to recognize it) 

any idea why its not appearing?
thanks in advance ✌️

**Comment by jcooray** [comment]
I am on Windows 10 1909 and also initially experienced this problem where the _Setup OpenXR_ option was not displaying in the WMR Portal settings...

And then I checked installed apps in the Win 10 Settings App.... and _Microsoft OpenXR_ was already shown as installed....

At that point I realised 2 things:

1. I don't ever remember installing it myself ( and certainly not the WMR portal)
2. I had seen it installed for quite some months in the settings app and had previously come to the conclusion that it had been installed as part of a Windows Update.

I do not suffer from the judder problem (in fact, I am awed at how well it runs and I have a Reverb Pro like you).  However, I can explain what happens visually when OpenXR apps start (they look visually different to when SteamVR apps start:

- SteamVR: "chimes sound" followed by the WMR home being replaced by wireframes triangles against a black background which resolve into the steam home / app

- OpenXR: the same as above but the initial background is _blue_.  Also, the SteamVR status window is not displayed (because SteamVR never starts and is not needed)

Hopefully, the description above can help you determine if SteamVR is really running after all

**Comment by ODEH67** [comment]
> And then I checked installed apps in the Win 10 Settings App.... and _Microsoft OpenXR_ was already shown as installed....

i checked that out and u'r right it was already installed ,

> 2\. I had seen it installed for quite some months in the settings app and had previously come to the conclusion that it had been installed as part of a Windows Update

 yeah sometime in 12-15 of June which is before the new update of the "new clamed" openxr released. so i reset it and then deleted it , after that reopening the mixed reality portal and automatically it notified me that the openxr is installed and it is available to be activated in the portal....
![Screenshot (57)](https://user-images.githubusercontent.com/63449828/87256232-12a00380-c491-11ea-8bd6-73429fa83c61.png)

by activating it once it will not going to appear again.

> I do not suffer from the judder problem

did u suffer the judder and ghosting problem before this openxr update?

> * OpenXR: the same as above but the initial background is _blue_.  Also, the SteamVR status window is not displayed (because SteamVR never starts and is not needed)

when do u exactly experience this or see it? when launching a game or just plugging in the headset? because launching the portal or a game will always need to launch the steamvr in case that the game is from steam store of course , and in this case u will experience the srteam interface.. 
this what appears when i launch the game while the portal and steam vr are already opend...
![2020-07-12 22-58-38_Trim_Moment](https://user-images.githubusercontent.com/63449828/87256783-e935a680-c495-11ea-87da-55a17ace24ad.jpg)
![2020-07-12 22-58-38_Trim_Moment(3)](https://user-images.githubusercontent.com/63449828/87256811-11250a00-c496-11ea-9f8b-d4025137189b.jpg)

is tha how openxr interface opens or is it still the old interface?

**Comment by jcooray** [comment]
Those screenshots looks like OpenXR is activating.  It shouldn't matter if SteamVR is already opened - when an app has been developed for OpenXR then the OpenXR runtime will be loaded and anything displaying to the HMD prior to that (WMR home or SteamVR home will be replaced).

In my case, it looks like OpenXR had updated to whatever the current version is before the 1st time of running GTA R.E.A.L.  This may have happened as I had uninstalled and then re-installed WMR portal a few days prior due to issues I was having with WMR chaperone.... In that case I would have somewhat luckily have updated my OpenXR.. and when I installed Release 5 of GTA I was none the wiser and everything ran without a hitch!

Now whilst there isn't judder, there is some ghosting of moving objects depending on their relative speed to me.  I would expect that since this mod uses alternate eye rendering so the left and right images, not displaying synchronously, one of them will be interpreted as an afterimage / ghost.  I find this ghosting to be minor though (after all it only really happens when whatever I am looking out crosses some threshold of relative speed) and the overall wow effect of GTA with VR scale and stereo 3D makes it worth it.

I fully accept, somewhat like some people have greater sensitivity to framerate consistency or screen  tearing, that how much alternate eye rendering is perceptible is individual to the user though.  Native VR apps will display a left and right image that are rendering the  _exact same moment_ in the game simulation - GTA R.E.A.L can't do that.

**Comment by ODEH67** [comment]
> there is some ghosting of moving objects depending on their relative speed to me

exactly thats what im facing too .. specially by holding a rifle in first person view, by moving so fast u will see the real ghosting which would looks like duplicated image of the gun.. i will post a detailed post about this problem and how it looks like through the lenses

> this mod uses alternate eye rendering so the left and right images, not displaying synchronously, one of them will be interpreted as an afterimage / ghost

the main reason of this new release of the mod is to solve this rendering thing depending on the new openxr solution which microsoft claimed , but it seems that microsoft did not get the entire thing working as it suppose to

https://www.reddit.com/r/WindowsMR/comments/hezaeu/will_alternate_eye_rendering_needed_for_my_gta_vr/fwipzb7?utm_source=share&utm_medium=web2x

so what i understand now is this ghosting issue is not solved and it will remain till some-when comes a new update or an other method to avoid using the rendering thing... or simply buying a non-WMR headset which i can't specially that i pre ordered the new reverb G2 😅

**Comment by LukeRoss00** [comment]
@ODEH67 What Release 5 of the mod (switching to OpenXR rendering) was supposed to do has already been accomplished: making it possible for WMR users to experience the mod without the horrible judder that was present before due to limitations of the Microsoft driver for SteamVR.

The residual image doubling or ghosting (visible only on objects that are moving laterally at some speed) is unavoidable with alternate eye rendering: non-WMR headsets do not make it any better, and neither I nor Microsoft can do anything else about it.

**Comment by ODEH67** [comment]
> the main reason of this new release of the mod is to solve this rendering thing depending on the new openxr solution which microsoft claimed , but it seems that microsoft did not get the entire thing working as it suppose to

@LukeRoss00 the mod works fine and it does it job ... but what I meant by that , that Microsoft has not literally solved the rendering issue like we expected from their post in reddit, or at least as i expected ... 

> non-WMR headsets do not make it any better

so this ghosting issue is also presented in the non-WMR headsets
