### ISSUE TITLE
The game is launching in desktop instead of inside VR Oculus Rift

### ISSUE THREAD

**Issue by rockysilver** [LukeRoss00/gta5-real-mod#231]
Hello,

I followed the instruction step and step, fresh install; but when I tried to launch the game from steam, the game would launch a small square on my monitor instead of inside my headset. When I wear my headset, all I see is oculus home, and no control on the game.

Any help is appreciated, thanks!

**Comment by ODEH67** [comment]
i dont have an oculus headset but in order to work , steam vr and oculus should be launched before running the game ,,, extra tip try the older version of the mod release 4 or just the older version of the scripthook V, maybe the newer version was focused more on the wmr headsets (XR) and Epic games version of the game
https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r4

**Comment by LukeRoss00** [comment]
@rockysilver Which headset do you have? Also, let's see if your directory structure is correct. Open a command prompt, and enter the following commands:

```
cd C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V
dir /s > dir.txt
```

Then attach the resulting file `dir.txt` which will appear in the game folder.
