### ISSUE TITLE
Game crashing after loading

### ISSUE THREAD

**Issue by zakh45** [LukeRoss00/gta5-real-mod#232]
Hi there,

I have GTA V on Epic Games and I'm using an Oculus Quest with Link. 

The game starts without the mod and is playable, and when I apply the mod and start the game and select story mode, it starts loading but then crashes just before the game starts.

Has anyone seen this issue before?

Thanks in advance

**Comment by ODEH67** [comment]
scripthook v version and the version of the game maybe?  from my own experience with an other headset (WMR HP Reverb) it happened only when I adjust the in-game settings or the resolution in the mod files, it crashes same as u or sometimes at the intro by launching the game , but after multiple tries it launches ,after that it does not crash anymore... so please make sure that u followed the instructions , a little bit of time to read it does worth it... 
first this :
https://github.com/LukeRoss00/gta5-real-mod

secondly : 
https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r5

if u tried to modify anything in the mod files before trying the mod, try to launch it from a clean install of the mod without any modifying ... specially if u have no other mods installed cuz it could impact if u dont install it correctly..
on oculus quest the mod does not work with Virtual Desktop but since u use the Link so it should work .. that is just in my opinion as a user like u .. would be appreciate if u give a feedback of what solved your problem for the community

**Comment by zakh45** [comment]
Thanks for the response. 

I had read through the instructions and set my settings to high, but I thought I'd download the Oculus Tray tool to change my audio settings as it was still coming through my soundcard during the intro. 

The only thing I actually ended up changing though was setting my Link preset to GTX1080i and restarting the Oculus services. Now the game is booting without any issue!

**Comment by LukeRoss00** [comment]
Great, thanks for getting back to us with your solution. It may be helpful for other users with the same problem!
