### ISSUE TITLE
Unplayable with wmr

### ISSUE THREAD

**Issue by magocaos** [LukeRoss00/gta5-real-mod#235]
Hey, in first place, thanks for this great VR MOD Luke!!!

I tried the setup step by step but when i am in a car and i turn rigth or left, everything is very blurry and fuzzy. Headtracking works perfectly but i can stand the most hard vr games and i dont feel any nausea. In fact, i dont feel sick playing this gta V(r) but it makes the experience so bad that i cant play. Objects that move quick also experience this unconfortable effect.

I think something is wrong with my system or maybe a 1070 is not powerfull enougth to keep the game playable at default medium settings...

Any ideas? I would love to play the game

**Comment by LukeRoss00** [comment]
First of all, make sure that you have your `Windows Settings> Mixed Reality> Experience Options` set to `Best visual quality`, so that motion smoothing won't randomly activate itself (it doesn't support alternate eye rendering).

Next you'll want to check your frame rate. The mod has a built-in frame counter, which you can activate by pressing `F11` and then `N` with the GTA V window in focus (see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys for more details). If you're not hitting 90 fps consistently, consider lowering your graphics settings until you do, and/or switch to monoscopic mode.

**Comment by ODEH67** [comment]
from a personal experience as a WMR user , the way u go low with the settings the best u get less of this ghosting effect , u mentioned u have a gtx 1070, well it depends on your setup and the headset too (which it is always helpful if u provide more details about your setup to determine the issue easier and faster)  .. for example i got Hp Reverb with 2080 super , with low settings (and adjusting only the resolution values of the mod from 600 to 1200) I still experiencing this ghosting issue too but it still of course playable .. as Luke told me before the ghosting thing is not avoidable because of the (alternate eye rendering)... try the Author solution and a feedback will be appreciated

**Comment by magocaos** [comment]
> from a personal experience as a WMR user , the way u go low with the settings the best u get less of this ghosting effect , u mentioned u have a gtx 1070, well it depends on your setup and the headset too (which it is always helpful if u provide more details about your setup to determine the issue easier and faster) .. for example i got Hp Reverb with 2080 super , with low settings (and adjusting only the resolution values of the mod from 600 to 1200) I still experiencing this ghosting issue too but it still of course playable .. as Luke told me before the ghosting thing is not avoidable because of the (alternate eye rendering)... try the Author solution and a feedback will be appreciated

thank you ODEH67. I play on a heavely modded Lenovo explorer (bigger sweetspot and 105º vertical and 105º wide FOV, studio headphones and extra room for the nose and forehead).
I tried the in-game multiplier as Luke said.. 2700x2700 and 2000x2000 in medium settings. I will try low config. I am a optimization fan and i always get every game working perfectly smooth and looking good, so lets see if i can get this running ok as expected.

I will try low profile with different resolution values.

**Comment by magocaos** [comment]
well. I try everthing and finaly disabled stereoscopic rendering, as luke ross sugested. And i can still feel the deepness of the world. I use low profile with 900x900 (which is 2300x2300 aprox.) due to the 2.5 supersampling resolution.
It now feels smooth, and clean. Each time i start stereo rendering, the double vision/ghosting destroys everything and i cant play. I tried 600x600 but estereoscopic rendering makes the game unplayable. Even with a subtle movement, i find the image suffering in sharpness in the stereo mode. Not only that, the extra work that stereo needs help with extra sharpness and smoothness  of the game

So, for me the game is so much better in monoscopic mode, and i still apreciate the scale and deepness of the world. 

Riding a motorbike in offroad conditions make me a little dizzy after half an hour, but i enjoy it!


Thank you all for the suggestions
