### ISSUE TITLE
Game Crashes After Selecting "Story Mode" After Launching The Game

### ISSUE THREAD

**Issue by AtozZ000** [LukeRoss00/gta5-real-mod#252]
CPU:i7 4790
GPU:RX 590
VR headset model: Rift S
game version and build: Latest Rockstar Version, I dont know the exact build.
release of the mod: r6
did you follow all the Quick setup steps carefully, in particular step 4?
Yes.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat?
I Tried L and M
did the batch file report any errors?
No
did you change the graphics settings manually?
No.
are you using any other mods?
No.

I've Reinstalled the mod 2 or 3 times, following instructions very closely and still, my game crashes after I select story mode. Earlier I was able to get the mod working but now it doesn't for some reason...

**Comment by Eddie557** [comment]
Yeah Me too the Same fresh reinstalled and no luck with the mod version r6

**Comment by LukeRoss00** [comment]
Let's see the log files: add the line `RVRLog = 2` at the end of your `RealVR.ini` and run the game until it crashes. There will be a new `RVRLog.txt` file in the game folder: please attach it here together with your `asiloader.log` and `ScriptHookV.log`.

**Comment by AtozZ000** [comment]
here are the logs from my most recent attempt with VR.
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5209870/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5209871/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5209872/asiloader.log)

**Comment by kraehdev** [comment]
Same here. While loading, at some time the music starts to stutter and the game crashes.
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5210022/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5210031/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5210032/asiloader.log)

**Comment by LukeRoss00** [comment]
@AtozZ000 Your log file shows that you are using the wrong graphics settings (1280x1024 resolution instead of a square window, no frame scaling, ...). Are you positive that the batch file gave you no errors? You could also check your `settings.xml` manually, and/or post it here, to see whether something looks wrong.

There is an extra Present() call for each frame in your log that might indicate some overlay interfering with the program.

@kraehdev I see no obvious problem with your logs, except for the fact that the game is taking a very long time to load (2 minutes, it should be half of that). Does it also happen without the mod?

**Comment by carn1x** [comment]
I've been having this problem lately too. I'm on Ryzen 2600X + 5700XT. I run the batch file before each play and I can get into the game. I need to always reduce scaling considerable to 1.25 I think to get acceptable performance, which applies fine without restart however if I exit and start the game again I get a crazy after Story Mode appears to load and it crashes to desktop after the first "frame" of the world. It seems like the act of saving the in-game settings corrupts the settings in a way that the VR mod doesn't like even though I'm only modifying a single setting.

**Comment by LukeRoss00** [comment]
@carn1x That's interesting, Never happened to me, it could be a problem introduced by a recent game update. Could you by any chance post your `settings.xml` file before and after tweaking the graphics options in game, so I can check what gets corrupted or changed?

Also, everybody who's got this issue: could you post your `commandline.txt` file from the game folder?

**Comment by DavidJelinek** [comment]
I have Quest and 
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5211771/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5211772/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5211773/asiloader.log)


Epic version v1.0.2060.1

**Comment by LukeRoss00** [comment]
@carn1x Oh sorry, one important detail from your comment that I didn't notice at first: you mentioned setting frame scaling to 1.25x, but the mod can ONLY work reliably if frame scaling is 2x or 2.5x. If you want to improve performance, the right thing to do is lower the base window resolution.

**Comment by tjcooke** [comment]
Also having this issue now after having successfully used this mod a couple days ago.

Headset is a Samsung Odyssey+ and I'm using the latest Epic Game Store release.

settings.ini is same as High with a couple of settings dialed down. 

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5211895/RVRLog.txt)

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5211896/ScriptHookV.log)


[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5211898/asiloader.log)

**Comment by PiousGalaxy** [comment]
Hi, Same issue tried to install today and have this issue. There was a recent update. tried on H M and L. no batch errors.
I7 7700
RTX 2070 S
Rift (Original one)

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5212260/RVRLog.txt)
s
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5212261/ScriptHookV.log)

a
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5212262/asiloader.log)

[commandline.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5212264/commandline.txt)

**Comment by kraehdev** [comment]
@LukeRoss00 :
Without the mod the loading always seemed long but it never crashed.

**Comment by carn1x** [comment]
Slightly off topic but I can't test due to ScripHookV needing an update (2060.1), but it seems others are able to get around this?

**Comment by Derek549** [comment]
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5212419/asiloader.log)
[commandline.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5212420/commandline.txt)
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5212421/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5212422/ScriptHookV.log)

Same problems as above, working with a default configuration GTA V and REAL r4. Am currently updating to r6 in order to test that.

Setup:
i7 6700k and GTX 1070
Rift CV1

**Comment by Eddie557** [comment]
RTX2080TI -  I7 9700    I cant get around it  i reinstalled  fresh copy of GTA 5 followed all the steps but theres been  a update.  
 ScripHookV  NEEDS  an update ( 2060.1)

**Comment by LukeRoss00** [comment]
So, one thing that all the logs seem to have in common is that Script Hook V detects version `VER_1_0_2060_0_NOSTEAM`, a.k.a. non-Steam 1.0.2060.**0** (you can see it on the 4th line of `ScriptHookV.log`).

Since the game was officially updated to version 1.0.2060.**1** a few days ago, I suspect that either:
- you guys have all unofficially downgraded to the previous version (strange that nobody mentions it though), and this is somehow causing conflicts, or
- Rockstar has forgotten to bump the version number for its non-Steam edition, and that is causing Script Hook V to crash because it thinks it can deal with this new game version while in reality it can't.

**Comment by Derek549** [comment]
@LukeRoss00 yes, can confirm I have the 1.0.2060.1 version of GTAV installed.

**Comment by PiousGalaxy** [comment]
I can also confirm my version is 1.0.2060.1

**Comment by Derek549** [comment]
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5212461/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5212462/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5212463/asiloader.log)
[commandline.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5212464/commandline.txt)

Latest logs running r6 on GTAV 1.0.2060.1

**Comment by LukeRoss00** [comment]
Okay, than the issue is clear: for non-Steam users, Script Hook V is wrongly detecting version 1.0.2060.1 as `VER_1_0_2060_0_NOSTEAM`, which is making the game crash because the .

I'm not aware of any way to downgrade non-Steam game versions, so my advice is to wait a few days until Alexander Blade releases a Script Hook V update on http://www.dev-c.com/gtav/scripthookv/

**Comment by ODEH67** [comment]
hello, It seems that is a scripthook V problem... a new update just released today check it out 👇,,,

http://www.dev-c.com/gtav/scripthookv/

and please give a feedback 👍

**Comment by ODEH67** [comment]
I just tested it with the mod v6 and the included scripthook V , it crashes as all of u mentioned . and I tested the new update of Scripthook V, it solved the problem, so I can confirm that

**Comment by bastienwcs** [comment]
@ODEH67 I replaced dinput8.dll and ScriptHookV.dll with the one you shared and it works flawlessly.

Thanks !

**Comment by Derek549** [comment]
Confirmed I've installed, tested, and works! Thanks @LukeRoss00 !

**Comment by PiousGalaxy** [comment]
can confirm working

**Comment by kraehdev** [comment]
yes, confirmed 👍 
Thanks @LukeRoss00
