### ISSUE TITLE
Unwanted head movements in vehicles, near clip plane, shake to reset & Vinewood tour FOV

### ISSUE THREAD

**Issue by DickDastardlyUK** [LukeRoss00/gta5-real-mod#26]
Hi,
Loving the mod, thanks so much for all your hard work on it - I've already enjoyed many hours of driving around Los Santos :). I did notice a few minor issues, however:

1. In most vehicles (e.g. Police Cruiser, Obey 9F Cabrio, Bravado Banshee, Vapid Bullet, Declasse Stallion) there's a small additional rightward translation of the head as you turn your head to the right of center. This is fairly subtle and not a huge deal. In some vehicles, however, there's also an additional unwanted vertical translation which is more noticeable and annoying. In these, when you look straight ahead and then turn your head to either side your viewpoint rises, and then falls when you return to looking straight ahead (e.g. Coil Voltic, Declasse Torrado, Canis Mesa, Imponte Ruiner, Dinka Blista).

2. In vehicles with roofs, the nearest part of the roof or side window often clips when looking up or to the side. Is there any way to adjust the near clip plane to prevent this?

3. I occasionally find myself accidentally triggering the "shake head to reset view" when looking around. Is there any chance you could add a hotkey to disable this feature?

4. If you ride the open topped Vinewood tour bus in first person view, the rendered FOV is incorrect (too zoomed in). If you switch to the third person perspective, rotating your head causes your view to orbit the bus rather than working the way it does with player controlled vehicles.

Cheers,
Mike

**Comment by cercata** [comment]
>If you switch to the third person perspective, rotating your head causes your view to orbit the bus rather than working the way it does with player controlled vehicles.

This happens algo in some misions, for example in Meltdown when you go on the limo, and when camera changes, if you are not looking forward, camera doesn't point to the point of interest anymore.

That would be nice if he can improve that, but we can live with it if he's busy making the VR mod for RDR2 ;)

**Comment by LukeRoss00** [comment]
> [...] unwanted vertical translation which is more noticeable and annoying

Yeah, I agree that it can be annoying, but the game does it on purpose ("it's a feature, not a bug!") to let your sight be uninterrupted by the specific vehicle features (seats, handlebars in quads and bikes, ...) and to avoid the camera clipping. It would be hugely complex, and not really something I'm interested in, to mod every possible vehicle in the game to make this effect subtler or get rid of it completely.

> In vehicles with roofs, the nearest part of the roof or side window often clips

The near clip plane is already pretty close to the eye (some users would even say uncomfortably close), and in any case with position tracking at some point the camera will inevitably poke through solid surfaces. Have you tried disabling position tracking with the hotkeys? That might be the only fix available, because I don't believe anyone has find a way to control the gameplay camera near clip plane.

> I occasionally find myself accidentally triggering the "shake head to reset view" when looking around. Is there any chance you could add a hotkey to disable this feature?

Weird, you're the only user reporting that! Some were unable to trigger the headshake, but nobody found it too sensitive. What frame rate do you usually get? When does it happen?

> If you ride the open topped Vinewood tour bus in first person view, the rendered FOV is incorrect (too zoomed in). If you switch to the third person perspective, rotating your head causes your view to orbit the bus rather than working the way it does with player controlled vehicles

Yep, that script has a totally wicked camera. 1st person is useless anyway during the ride (you have like the worst seat in the bus, totally blocked) and 3rd person has a custom camera that I cannot fix. Like with the limo, just recenter by shaking your head when the view drifts too much from what you want to see.

**Comment by masher42** [comment]
There is a workaround for the unwanted vertical movement in cars. When sitting in the car, press 'Y' to toggle heading control off. If heading control is disabled, no unwanted movement will happen. Unfortunately, it also disables the ability to aim with your head, so no shooting in this mode. It would be immensley cool if it could revert to 'heading control enabled' only when aiming. I also like to walk around with heading control disabled, because this way I can walk a straight line and look to the sides.

I have to say this mod is utterly cool. Thank you so much for making it and sharing it with us !

**Comment by LukeRoss00** [comment]
> There is a workaround for the unwanted vertical movement in cars. When sitting in the car, press 'Y' to toggle heading control off. If heading control is disabled, no unwanted movement will happen. Unfortunately, it also disables the ability to aim with your head, so no shooting in this mode. It would be immensley cool if it could revert to 'heading control enabled' only when aiming. I also like to walk around with heading control disabled, because this way I can walk a straight line and look to the sides.

You know what? I like that idea! Could you try [this](https://github.com/LukeRoss00/gta5-real-mod/files/3827141/RealVR.zip)? Just unpack it and overwrite the previous `RealVR.asi`. I made the changes on the fly and cannot really test them at the moment, so I would appreciate it if you let me know how they work for you.

```
Y           Cycle heading control (always, only when aiming, never) - always at start
```

**Comment by masher42** [comment]
Awesome. I'm glad you like the idea ! However, I just tried the file and it crashes the game. The crash happens right after loading and entering the world. I faintly see the first frames while the games fades in. It freezes and takes me back to the desktop with the launcher informing me that the game crashed. I copied back the original .asi file and it works again. Still, insanely cool that you put something up **that** fast.

**Comment by LukeRoss00** [comment]
Mmm... It might be because the two components of the mod are no longer matched. Could you also try overwriting d3d11.dll with [this one](https://github.com/LukeRoss00/gta5-real-mod/files/3827218/d3d11.zip)?

**Comment by masher42** [comment]
Yeah, that fixed it. And it's working ! But has issues. When in the car and aiming it works but when looking to the right the view is stuttering up and down. Strangely looking to the left is fine. When on foot it seems to work great, but I just tested it very briefly. I will do further testing, but this is already an improvement for my personal play-style. One downside is that you have to manually adjust the forward position very often when enter/leaving cars, but I suppose this is just the way it is, no big deal and it was like that before when disabling heading control.
