### ISSUE TITLE
Setting OpenXR to SteamVR using WMR there is issues with rendering ?

### ISSUE THREAD

**Issue by SilentChill** [LukeRoss00/gta5-real-mod#261]
I'm not sure if rendering is the correct term but the display doesnt show the  game properly and when the game loads only the map is showing but im still sat in Steam VR home.

It works perfect in WMR only, however I want to use a program for motion compensation which only works in Steam VR however when running in steam vr without openxr I get the blurry  stutters.   

Hope I expained myself properly , below couple fo screen grabs of what I can see in VR

![image](https://user-images.githubusercontent.com/28492034/95767671-02c0d700-0cad-11eb-8354-6148bf9ffe11.png)

In Game only the map showing ?

![image](https://user-images.githubusercontent.com/28492034/95767979-85e22d00-0cad-11eb-8edc-84aa676adaaf.png)

CPU: 9700k
GPU: 2080ti
VR headset model: WMR HP Reverb
game version and build: 1.0.2060.1
release of the mod: Release 6
did you follow all the Quick setup steps carefully, in particular step 4?
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M i think
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

**Comment by SilentChill** [comment]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5366989/ScriptHookV.log)


[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5367014/RVRLog.txt)


And wow the VR Log gets big very quick  after 5 minutes it was 5gb lol    i had to chop this one down to fit in here

**Comment by LukeRoss00** [comment]
Yes, unfortunately with WMR headsets the mod does need OpenXR to work correctly. I'm afraid that's not going to change, because the Microsoft runtime has a subtle issue with SteamVR that makes tracking unstable when alternate eye rendering is used, and Microsoft is probably never going to fix it—especially now that even Valve is moving to OpenXR.

Which program would you like to use for motion compensation?

**Comment by SilentChill** [comment]
Yeah I thought as much, maybe when the the Reverb G2 comes out they may fix these issues but I won't hold my breath.

Program im using is this  https://ovrmc.dschadu.de/

Without it I'm floating around inside vehicles

**Comment by LukeRoss00** [comment]
Seems awesome! Who knows, maybe sooner or later they will come out with an OpenXR version, now that the industry as a whole seems to be (slowly and grudgingly) moving toward OpenXR...

**Comment by ODEH67** [comment]
hello guys, so I was wondering if your problem was fixed @SilentChill  cuz I got that issue once and fixed it... If u meant the game itself dont launch at all while using the openXR , as it seems in your photos there is that (fix it) Button which it tells u that there is an issue whith openXR. just click it and follow the steps afterwards and it should work ..

**Comment by SilentChill** [comment]
@ODEH67 it works fine if I use it in WMR but I want to use it in steam vr as I have a program I want to use .

Just one of those things that may never be fixed  unfortunately
