### ISSUE TITLE
Height in vehicle

### ISSUE THREAD

**Issue by Raging-Beard** [LukeRoss00/gta5-real-mod#262]
Hey awesome mod :) this isn't an issue really but I was wondering is there anyway to change default height in vehicles? I am always too high.

Also is there a way to disable head shake to re-enter? I have had this happen a few times now when I didn't want it to (in police chases) and would love to be able to bind a button instead.

Many thanks!

**Comment by LukeRoss00** [comment]
Thank you! The head position when you enter vehicles (including the default height) is set by the game and not by the mod. It could be modded, but it's a huge nuisance because every single vehicle has its own customized head position, and there are hundreds of them. My advice is a quick trick: crane your neck up while you recenter after having entered the car, so when you slouch back in your seat the in-game head position will follow you down :-)

Disabling the headshake gesture: very few users have the spurious triggers problem, so it's not customizable via an option. However, you can permanently disable it in your copy of the mod by using a hex editor on `d3d11.dll` to change the byte at offset 2D6A63 from 3F to 4F.
