### ISSUE TITLE
Not an issue, more of a comment

### ISSUE THREAD

**Issue by BiovizierMantrid** [LukeRoss00/gta5-real-mod#268]
Sorry if this isn't the best place to message you. I very much am enjoying your GTA5 VR mod.  Everything works great; the only issue I had was in getting it to run. The game was crashing during the game load screen. Some minor digging led me to your release notes on release 6, which mentioned keeping ScripHookV up to date. The one in the release 6 rar wasn't working for me; once I replaced it, all is well. I assume that was the issue anyway. I think the game version now has a 'point one' in the number. So my piddly gripe is that it would be helpful to stress this point about the hook in the install instructions. I'm pretty persistent, but I imagine some others aren't so patient and might give up on the mod.

Beautiful Work! It must be nice to be proficient at coding.

**Comment by LukeRoss00** [comment]
Thanks for your kind words! You're right, the warning about the need to keep Script Hook V updated should go into the README too, although it's already in the release notes. I will put in an additional comment.

However, I don't understand why the game was crashing for you. I just tried again on my Steam copy to check, and if Script Hook V is not up to date it brings up a nice error message explaining exactly what the problem is:

![Snapshot](https://user-images.githubusercontent.com/34809409/98443431-7b2f8200-210b-11eb-8fca-8be48b78b780.png)

Didn't the message appear for you?

**Comment by BiovizierMantrid** [comment]
Forgot to say, I have the Epic version
