### ISSUE TITLE
Game Crashes after update

### ISSUE THREAD

**Issue by switelolo124** [LukeRoss00/gta5-real-mod#271]
Hi! 
I update script hook and files from last update of your relase.
Deleted all ASI i dont need for now, left only RealVR and OpenIV, if i remove realvr.asi, game load fine. Game crashes in about minute when load single player. I try change settings (betwen low, medium and high) even put my old settings before update but still nothing. Also restarting computer (just to be shure).
I have a rockstar launcher version, oculus home and cv1, i also verify files trough launcher. What should i chceck else? 
There are logs from asi and scripthook:

// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FFE3A640000
API: "DirectInput8Create" => 00007FFE3A642230
API: "DllCanUnloadNow" => 00007FFE3A655220
API: "DllGetClassObject" => 00007FFE3A655330
API: "DllRegisterServer" => 00007FFE3A664740
API: "DllUnregisterServer" => 00007FFE3A6649C0
LOADER: Loading *.asi plugins
ASI: Loading "F:\Grand Theft Auto V\OpenIV.asi"
     "OpenIV.asi" => 00007FFE55150000
ASI: Loading "F:\Grand Theft Auto V\asi\RealVR.asi"
     "RealVR.asi" => 00007FFE54330000
LOADER: Finished loading *.asi plugins

// GTA V SCRIPT HOOK (build Aug 16 2020, v1.0.2060.0)
//     (C) Alexander Blade 2015-2020
[20:49:07] INIT: Started
[20:49:07] INIT: Success, game version is VER_1_0_2060_0_NOSTEAM
[20:49:07] INIT: Registering script 'RealVR.asi' (0x00007FFE5433A310)
[20:49:23] INIT: wnd proc 0x00000000FFFF0713
[20:49:23] INIT: IDXGISwapChain 0x00007FFE09F4D960 (0x00007FFE09D358B0)
[20:49:23] INIT: IDXGISwapChain set
[20:49:23] INIT: DX init started
[20:49:23] INIT: DX feature level B000
[20:49:23] INIT: DX init succeeded

**Comment by LukeRoss00** [comment]
The logs look fine. First thing I would try is to also delete `OpenIV.asi`. It's not incompatible with my mod, but it could be loading other mods which make the game crash.

If that doesn't work, use a text editor like Notepad to add a line `RVRLog = 2` to the `RealVR.ini` file, and attach (don't copy) the resulting `RVRLog.txt` file here.

**Comment by switelolo124** [comment]
Yes sir! 
I did delete openiv.asi too, left only realvr and result was the same. 
PS. Every driver is updated, i deleted every mod i have installed, and one thing - when game crashes its just close. Windows does not report error message or anything, same in launcher. 
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5532727/RVRLog.txt)

**Comment by LukeRoss00** [comment]
The log shows that your game crashes as soon as it enters story mode. `RealVR.asi` doesn't even get loaded, because the game crashes before that. So it doesn't seem that VR is the problem.

I know that you said that you already verified the game files, but there must still be something wrong with your installation. I advise removing my mod to check whether in 2D the game can load story mode correctly. If it doesn't, there are probably some remnants of other mods in the game folder that prevent GTA V from starting.

I also see that Script Hook V reports that you are using `VER_1_0_2060_0_NOSTEAM`, which is strange, as the original game should currently be updated to version 1.0.2060.**1**.

**Comment by LukeRoss00** [comment]
Are you using the latest Script Hook V from http://www.dev-c.com/gtav/scripthookv/ ?
