### ISSUE TITLE
Game crashes when first loading into story mode

### ISSUE THREAD

**Issue by tryaboy** [LukeRoss00/gta5-real-mod#277]
I first want to say thanks for the time and effort put into this mod. I've been really wanting to play through GTA V again and this seemed like the perfect thing to use to do this.

I am having issues getting it going though. After some initial bumps getting the game to launch, I now get to the point where I'm starting the Story Mode. The game displays, "Ludendorff North Yankton 9 Years Ago" and then kicks me back to the Oculus Home environment. I searched through the issues and I found a similar thread but it ended with no resolution. Below are my specs and logs:

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5609670/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5609673/ScriptHookV.log)
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5609674/RVRLog.txt)

CPU: **i7-4790**
GPU: **NVIDIA GeForce GTX 970**
VR headset model: **Oculus Rift**
game version and build: **Epic Store, 1.0.231.0**
release of the mod: **R6**
did you follow all the Quick setup steps carefully, in particular step 4? **Yes**
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? **First H, then L**
did the batch file report any errors? **No**
did you change the graphics settings manually? **No**
are you using any other mods? **No**

Any help is appreciated!

**Comment by LukeRoss00** [comment]
Hi and thanks for providing the logs!

You wrote that you're using Release 6, but the log says that you're still on Release 4. Please check that you extracted the latest files in the correct directory and that WinRAR doesn't give you any errors during extraction.

The Epic version sometimes gives people trouble because the game directory is not writable without admin privileges (unlike Steam, which always make game folders behave like normal folders even though they are under `Program Files (x86)`). One possible solution is to give your user full control to the directory `C:\Program Files\Epic Games\GTAV` so that WinRAR and the batch file will be able to work properly.

**Comment by tryaboy** [comment]
I will try this and report back. Thanks!

**Comment by tryaboy** [comment]
You are correct. Somehow I had grabbed R4 instead of R6. Once I copied in the R6 files, the game loaded. Thank you very much for your help. I really do appreciate it!
