### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Faburden** [LukeRoss00/gta5-real-mod#286]
Specs:
RX Vega 64
Ryzen 5 3600
Oculus Quest 2
Mod Version 6

For some reason, my game is running at 5 fps whenever I run it with the mod.
I've reinstalled it tried again, followed all the steps, and no luck.
Inside the headset, it's very laggy and stuttery and it's like a screen following wherever I'm looking.

**Comment by firepanther911** [comment]
it happened to me too. it use to never be this way. i tried it on oculus rift s and valve index and the same thing 5fps, very lagging and choppy. not playable at all. all of this happened about 5 -7months ago when GTA made a major update.

**Comment by LukeRoss00** [comment]
I released a new version of the mod back in August to solve this specific problem which was caused by a game update. Please make sure that you are actually using [Release 6](https://github.com/LukeRoss00/gta5-real-mod/releases) of the mod; in case it still doesn't work, extract the mod files from Release 6 again into the game folder and be careful to check that you are actually overwriting the old files.

**Comment by Faburden** [comment]
Already tried that once and yes, I am definitely using release 6 of the mod.

**Comment by firepanther911** [comment]
I  downloaded the latest mod from your site. It didn't work.  Now gta put
out another update again

**Comment by celowsky** [comment]
@firepanther911 you can try reverting your GTA V version by following the instructions and downloading the old GTA executables linked in this video: https://www.youtube.com/watch?v=9d0GjeUHSUA.

**Comment by firepanther911** [comment]
Thank you very much for your assistance in this matter. I would like to donate some money. Do you have a link? Sent from Mail for Windows 10 From: Christian ElowskySent: Thursday, December 17, 2020 2:38 AMTo: LukeRoss00/gta5-real-modCc: firepanther911; MentionSubject: Re: [LukeRoss00/gta5-real-mod] Not Working (#286) @firepanther911 you can try reverting your GTA V version by following the instructions and downloading the old GTA executables linked in this video: https://www.youtube.com/watch?v=9d0GjeUHSUA.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LukeRoss00** [comment]
I'm not taking donations at the moment, but thanks for the offer!

**Comment by firepanther911** [comment]
I noticed the new scripthookv . Is there a way to revert back to the new
updated version? Or do I have to download it again?

**Comment by firepanther911** [comment]
what is missing shell DLL cshell.dll. mean for your no one lives forever mod? I tried to start the game and it gave me this message. Sent from Mail for Windows 10 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by AVG antivirus software.
				www.avg.com

**Comment by firepanther911** [comment]
Hey luke ross, I tried starting up your No one lives forever vr mod and I got this message on the attachment. How can I fix this? Was able to play the game before. Sent from Mail for Windows 10 From: Derrick taylorSent: Saturday, December 19, 2020 6:49 AMTo: LukeRoss00/gta5-real-modSubject: Re: [LukeRoss00/gta5-real-mod] Not Working (#286) I noticed the new scripthookv . Is there a way to revert back to the new updated version? Or do I have to download it again? On Sat, Dec 19, 2020, 6:02 AM LukeRoss00 <notifications@github.com> wrote:I'm not taking donations at the moment, but thanks for the offer!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
