### ISSUE TITLE
[Not an issue] Thoughts of the mod on a RTX 3080

### ISSUE THREAD

**Issue by Dark-CSS** [LukeRoss00/gta5-real-mod#290]
First of all, sorry to be opening a issue for this, idk if it's against the rules, advert me if it is and I'll move this post to reddit or some other more adequate place for discussions. I just made a massive hardware upgrade and want to share some thoughts with fellow GTA V real vr mod users and (hopefully) the developer, Lukeross00.

So, I recently got a RTX 3080 and a ryzen 3600X, I've been playing the GTA V VR mod on a Rift S. All settings are maxed out except reflections (which I put in normal because I dislike how they look at ultra) and grass (which I also put on normal because they're laggy). MSAA is set to 4X and FXAA and TXAA are disabled cause I think they make the game blurry.

I can run the game at these settings at the cap of 80 fps of my Rift S with an average of 70% GPU usage, which goes up to 100% depending on the areas. The game looks absolutely stunning and fluid with this hardware and settings, there's only one downside: the stereo mode (alternate eye rendering). Without it, everything is perfect but without 3d and with a limited field of view.

Even with 80 fps and a lot of GPU headroom, the stereo mode (alternate eye rendering) increases the motion to photon latency my overlay shows by about 20 ms, but I feel as if my FPS has dropped below 60 because everything looks very jittery. It's ok to walk slowly on the street with it on, but as I do something more intensive like driving I start to feel motion sick. 

So I would like to know if someone has any tips for make the stereo mode (alternate eye rendering) more tolerable and ask if in the future could there be improvements that make stereo mode less laggy or are we in the state of the art of that feature?

**Comment by LukeRoss00** [comment]
Hi @Dark-CSS, no problems at all discussing that here even though it's not strictly an issue.

My take is that, as you said, for the moment we're pretty much at the state of the art with alternate eye rendering. Even with the RTX 3080, which is a mighty beast that only very few people have been able to get their hands on due to the semi-paper launch, you measured 100% usage in some areas.

In order to disable alternate eye rendering, you should be hitting a consistent 50% GPU usage (even less actually, to keep some headroom to avoid missed frames). Let's say no more than 45% GPU usage. At that point, the card would have the horsepower to draw the 160 fps needed to achieve true stereo rendering. And even if a new miraculous card somehow achieved that, it might well be that CPU would become a bottleneck at 6 ms per frame: especially actions like driving fast through the city where the game has to stream in a lot of textures and geometry would become choppy, as is happening for instance with Watch Dogs: Legion even in 2D.

So, I don't think that for all of 2021 at least we will have a system capable of running a stable 160 fps (or even 180 fps for headsets that refresh at 90), and I still believe that alternate eye rendering is the only viable solution.
