### ISSUE TITLE
Natural vision mod

### ISSUE THREAD

**Issue by Jesusavestill** [LukeRoss00/gta5-real-mod#291]
Does the lukeross real mod work with the complete natural vision mod ?

**Comment by rikiwelche** [comment]
natural vision Remastered works very well of course my version and gives a very nice rendering. I had tested mvga but I was not sure that it is functional whereas natural vision Remastered is indicated when loading the game by a logo.

**Comment by Jesusavestill** [comment]
What about nve ?

**Comment by rikiwelche** [comment]
Have you a  version of nve?

**Comment by Jesusavestill** [comment]
Yes, I do. But I think it’ll drop my FPS so I won’t install it.

**Comment by rikiwelche** [comment]
ok cool you took a subscription, the best is to try, there is always a way to go back ... the worst would be that a component is not compatible with the real mode ... what is your config ?
I would be curious to see ke resusltat ...

**Comment by Jesusavestill** [comment]
Ok, I'll check it out. Only partial nve was compatible.Not sure if it’s all
compatible since the vr mods updates. I bought a month to get the mod. I do
t want to chance wrecking my game or the vr experience by trying to install
again. Think the vanilla is fine and gives me plenty fps.The lighting was
very cool and sky.Especially the night sky Milky Way.Best with nve was
under water...looked like a crystal clear Atlantis.

**Comment by rikiwelche** [comment]
I play with the remastered mod and already I am delighted with the effects so I imagine with envolved ... if it works ... I personally have an rtx 2060

**Comment by Jesusavestill** [comment]
Nice!
It’s a lot more,bigger and better than the remastered.It’s worth ten bucks.

**Comment by rikiwelche** [comment]
10 dollars a month?  i saw the quality in videos but i only play in vr and nothing guarantees that i will work .. except you maybe!

**Comment by Jesusavestill** [comment]
No, sorry. You pay the monthly fee and cancel after you get the mod.

**Comment by Jesusavestill** [comment]
It works in vr but again not sure if the entire mod file works with the
lukeross real mod.

**Comment by rikiwelche** [comment]
ok then maybe i'll test this and keep you posted because i just started story mode so i won't lose much in case, thanks for your answers

**Comment by rikiwelche** [comment]
and you luke, do you have any information on the compatibility of this mod with yours? I would mind investing when I only play gta in vr ...
thank you

**Comment by LukeRoss00** [comment]
@rikiwelche The graphics overhaul mods like NaturalVision work fine in VR as long as you don't use ReShade or ENB (see https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking for more details).

**Comment by rikiwelche** [comment]
i took a gold subscription from razed and i'm testing its mode with real, without enb and reshad. I will tell you what it gives. I spoke with razed who told me that he will also make a vr compatible version of his mode, he finds it a shame not to play his mode without enb because it does not necessarily represent the work he offers. told me that he had tested it in vr with enb at the time and that it worked ... I would inform you of the result of my tests.

**Comment by Jesusavestill** [comment]
Cool, thanks!

**Comment by rikiwelche** [comment]
Here is the result of my tests,
 I installed the nve mode after a Reinstallation of the game, only the oiv file and not the enb folder nor the other so called necessary, but I have no vr vision, only the menu and the map ... I also tried  first install vr mode before nve ... Idem.
 On the other hand, the nve mode caused the game to crash when loading, I solved this problem by changing the game config.xml file in the mods folder (by a version found on the gta5mods site).  I have discussed this problem with rased, he tells me that his install just copies this file to the mods folder but I think a change still needs to be made because the game works without any mode.
 He M also said that L enb is installed only if you copy the files from the enb folder.
 On the other hand, once the 2 modes are installed, even if you uninstall nve, there is no way to have a vr vision.  You have to reinstall the game.
 I don't understand what is wrong.  Razed tells me to ask you (Luke) what might be the cause.  I have checked all the conditions necessary for real to work (no longer redone on.bat).
 Is there a way to find out why the vr is not working?  (log file ...).  The nve mode works without vr .... Is this because the 2 modes modified the same files?

**Comment by LukeRoss00** [comment]
@rikiwelche Could you attach your `asiloader.log` and `ScriptHookV.log` files here?

**Comment by LukeRoss00** [comment]
From another issue, it seems that user @DaDrop was able to make NVE work in VR (without ENB of course): https://github.com/LukeRoss00/gta5-real-mod/issues/78#issuecomment-648309849

**Comment by rikiwelche** [comment]
Ok thank you for the info I will give you the files as soon as possible and study what is said on your link.

**Comment by rikiwelche** [comment]
hello luke, how can i share these files with you, i don't see a link to insert a file?
thank you

**Comment by rikiwelche** [comment]
here 2 mega links
https://mega.nz/file/NQ8jXIwC#9tsGdUBZJADAUI1JKyG54mW2pwzFovJYvCihtodTyGQ
https://mega.nz/file/0FthGa5Y#dwwxlsLdi7KDlQOs1P90sIvHS0NF6xxNkW0e0PkVM8I
if it works...

**Comment by Jesusavestill** [comment]
Thanks, I'll check them out. What are these file links anyway ? Is this the
nve files for working vr ? But nve costs money.

**Comment by rikiwelche** [comment]
no these are my log files so that Luke can analyze them because nve does not work in vr.

**Comment by LukeRoss00** [comment]
@rikiwelche From your logs it is clear that you are using a pirated version of the game. You should have mentioned that right away, because the crashes and problems that you are experiencing are caused by that. I'm sorry but I can't give any support in this case.

As already mentioned, NVE works fine with my mod as long as you have the latest, legit version of GTA V and you don't install ENB.

**Comment by rikiwelche** [comment]
Ok Sorry for the inconvenience ... mea culpa! ... but I am in the process
of buying an official version of the game in order to enjoy the 2 modes ...
and thank you again for your vr mode

**Comment by Jesusavestill** [comment]
Not long ago, Gta5 was free on Elic games.

**Comment by Jesusavestill** [comment]
https://www.gta5-mods.com/misc/gta-v-remake-beta#comments_tab
A really excellent visual mod.

**Comment by rikiwelche** [comment]
I have pay 9,50 euro, installation in progress on the social club

Le jeu. 7 janv. 2021 à 13:51, Jesusavestill <notifications@github.com> a
écrit :
