### ISSUE TITLE
Sniper scope too irratic at full zoom

### ISSUE THREAD

**Issue by freekanimal** [LukeRoss00/gta5-real-mod#312]
Hi Luke,
what an amazing piece of work you have produced, the experience is far better than a lot of games built for VR!
Hats off to you old son!
My issue is regarding head tracking when using a zoomed scope on the sniper rifle. It's completely unworkable for me as it stands as it seem every micro-movement of my head is magnified enormously and all I see is the cross-hair shaking vigorously.
I tried using the hotkeys to disable heading tracking temporarily though it doesn't seem to have an effect with the sniper rifle.
It means I can't pass the mission without skipping, and no doubt any future sniper predicaments, pretty much rendering the gun useless.

Thank you advance for any ideas, and thank you already for all that you've done

Rich

CPU: i5 2500k
GPU: AMD RX 590
VR headset model: HTC Vive
game version and build: 1.0.2189.0
release of the mod: 7
I am using Redux, Stance - crouch/prone and Menyoo mods

**Comment by LukeRoss00** [comment]
Hi and thank you for the kind words!

I know for a fact that all sniping missions are passable with gold medals, even though some can be challenging. With the VR mod, IMO sniping feels so much more realistic. to the point that at high zoom levels you can actually see your heartbeat moving the scope, just like you would in real life with a handheld rifle.

A few hints: firstly, both in combat and hunting, just resist the temptation to zoom in too much. It is easier to hit enemies or animals if you dial back on the magnification a bit, which will make the image much more stable and (perhaps) invoke a bit of aim assist from the game. I haven't been able to prove this definitely, but it does feel like zooming out some makes the game more tolerant to aim imprecision. Secondly, you should think of your headset as your rifle, and just like you would in real-life shooting, you want to make it as stable as possible. That could mean calming down in order to reduce involuntary movements, holding your breath as you gently squeeze the trigger, and also it helps a lot if you put your hand against the headset to stabilize it.

Also, it might be that the Stance - crouch/prone mod is having an effect on the rifle (I have never tested it), so you might want to try and remove it temporarily to see whether it makes any difference.

**Comment by freekanimal** [comment]
Cheers, Luke what a legend, I didn't expect such a helpful reply so soon.
I will try removing the stance mod tonight and see if it makes a difference, I totally get what you're saying about stabilizing it with hands etc, but its not just a little erratic, it's completely uncontrollable, I was trying to do the mission where you first meet Trevor and have to snipe out some lamps; I tried zooming back out to a level where its mildly stable but it's just not close enough, the light literally disappears. To be honest the prone mod doesn't work properly anyway, I installed it as a measure to remain completly in first person, as you've outline the cover system only really works in 3rd, where traditionaly in first person one would crouch to 'cover' but alas there is only 'stealth mode' in GTA which provides very little cover. Strafing does the job if you've got something to the side but its not always the case... Any ideas?

Again, much obliged sir, thanks in advance,

Rich

**Comment by freekanimal** [comment]
Nah, I removed Stance and no change. I also had Menyoo and Trainer V installed but it's not them either. Only thing left to try I can think of is get rid of Redux or maybe try a fresh install.
Cheers Luke

**Comment by freekanimal** [comment]
Nope. :(
Fresh install here we come...

**Comment by LukeRoss00** [comment]
If you do a fresh install please make sure to completely remove the game folder, so that no stale files are left over (but don't remove the folder under Documents where your save files are stored!)

**Comment by freekanimal** [comment]
But of course..Dya know what Luke, I think I must just have a shaky head. I just managed to pass the mission with your tips, holding my breath helped massively. Holding the headset with my hands was a lost cause as I had the pad with both L/R buttons pressed, but this lead me to something similar, slumping down in my chair and resting the head set firmly against the chairs back. Voila, passed first time.Cheers matey-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 07/02/2021, 20:23 LukeRoss00 <notifications@github.com> wrote:

   
  If you do a fresh install please make sure to completely remove the game folder, so that no stale files are left over (but don't remove the folder under Documents where your save files are stored!)
