### ISSUE TITLE
Multiple layers, simultaneous eye rendering

### ISSUE THREAD

**Issue by morallo** [LukeRoss00/gta5-real-mod#323]
Hello, I haven't tried the mod yet but I'm somewhat involved in a similar effort with the VR mod for X-Wing Alliance.

After reading your idea of rendering into multiple compositor layers, I was curious: how is it better than submitting the depth buffer to the compositor? I think ASW 2.0 can use this to do better reprojection. Also OpenXR supports this through a standard extension. Have you tried it?

About the simultaneous eye rendering, the way it's done in XWA is by hooking the calls to DirectDraw (yes, all 3D projections are done in CPU in the game engine) and basically reconstructing all the 3D scene from 2D projection. Then the separate view projection matrices are applied in vertex shaders and rendered again in GPU.
I have no idea how you are implementing it in GTA V engine, so probably it can't be done similarly but in case it can help in some way...

**Comment by LukeRoss00** [comment]
> After reading your idea of rendering into multiple compositor layers, I was curious: how is it better than submitting the depth buffer to the compositor? I think ASW 2.0 can use this to do better reprojection. Also OpenXR supports this through a standard extension. Have you tried it?

ASW 2.0, or motion vector smoothing as other APIs call it, is quite good when it works, but fails rather spectacularly as soon as the motion is large enough to fall out of the motion vector search area. And unfortunately, while driving fast in GTA V (or even just turning the camera with the mouse or controller) the "fails rather spectacularly" part happens several times per second, leading to horrible stuttering.

I tried really hard to like it on different occasions during these months, and every time I had to admit that it just doesn't cut it. For conventional VR games, where the camera moves slowly and the only fast rotation is coming from your head, ASW can be useful (even though it's never really artefact-free). But for GTA V, where the camera motion is intense, ASW can never quite keep up.

ATW is a different beast. It works for any amount of rotation (although you start seeing black bars on the sides if angular velocity exceeds a certain threshold) and it's completely artefact-free. The problem with it is that it can only cope with one solid rotation. That's why initially when I created the mod I was thinking that it might be beneficial to split rendering into three layers, corresponding to the three separate rotational frames that you typically get in a GTA V scene: objects attached to the camera, player's body/vehicle, and rest of the world.

> About the simultaneous eye rendering

Many months have gone by since I wrote the README, and even though GPUs did indeed evolve, sadly we're still far from the point where normal people who don't have a famous YouTube tech channel can access hardware powerful enough to allow simultaneous rendering in a game like GTA V. I just tested yesterday with an overclocked RTX 3090, and the maximum stable framerate that it can squeeze out of the game at VR resolutions and FOV is only 120-140 fps, depending on the area and where you're looking at. We're still too distant from the stable 180 fps that would be needed for simultaneous rendering to make it a viable solution.

Great job with the X-Wing Alliance mod BTW! Gotta try it one of these days :-)

**Comment by morallo** [comment]
All the credit for @Prof-Butts, he is the wizard. I only worked on improving SteamVR performance, and now trying to implement OpenXR.

You are probably right about simultaneous stereo rendering, but I believe the perf impact may not be 50%... But that doesn't mean it's feasible in any case.

**Comment by LukeRoss00** [comment]
For GTA V most of the GPU cycles are burnt shading visible pixels, so true stereo is basically 2x the processing power, and at VR resolutions the game is completely GPU-bound. Hence the need for alternate eye rendering.

For OpenXR and motion smoothing, I tested just a few weeks ago and Valve hadn't yet implemented `XR_KHR_composition_layer_depth` :-(
