### ISSUE TITLE
Decoupling / heading question

### ISSUE THREAD

**Issue by freekanimal** [LukeRoss00/gta5-real-mod#324]
This may want moving to issue #313 'Hotkey to disable vr looking for mod compatibility'
Firstly, could I ask the meaning of the function of the hotkey 'I - Toggle decoupled 3rd person camera'.
I don't know if my setup is broken but it appears that it has no difference in effect than 'Y - Cycle heading control'
Is it essentially the same thing but only affects the 3rd person view?
In which case, is it supposed to have an effect on 3rd person while in vehicle? As it stands, on my system it doesn't.
Like the scope with Y having no effect.
I'm all about the 1st person view and try to stay there but as I've played more I've realized some of the helicopter missions where you have to drop things in a certain place are extremely hard not seeing around the vehicle Also planes are so much more fun to fly in third. I cannot understand why you'd want your whole view to shift around in this mode when you move your head and see nothing but a hindrance which leads me to think is it supposed to be like this or a bug in my setup?
Sorry if I'm becoming an annoyance with this heading thing.
Thanks in advance!

**Comment by LukeRoss00** [comment]
The easiest way to see what the `I` hotkey does is while you're on foot in 3rd person. The normal behavior of the mod is to decouple the camera orbital movement from the head rotation, so that you control where you're looking at with your head in a natural way, and you control where the camera is relative to your character with your mouse or right stick. If you press `I` this decoupling is toggled off, and you revert to the normal behavior of the game camera which is to link the direction where you're looking at with the camera position around your character. This lead to the fact that as you look around with your head the camera will also move in space; most people find this annoying, so it's off by default, but I left the hotkey to experiment.

I agree about the heli missions where you have to drop or pick up stuff (like Trevor from the water), they are really tough in 1st person! I managed to pass them all, and it does give a realistic feeling of how hard it is to actually hold a chopper steady over a target that you can't even see, but switching to 3rd person makes them so much easier!

**Comment by freekanimal** [comment]
Never mind, I just completed it, can you do GTAIV now? lol Only joking, massive thanks again man, you made one of the best games in the world infinitely better, and your support has been amazing, a living legend you are!
-freekanimal out
