### ISSUE TITLE
Suggestion: Add WMR setup to the main ReadMe

### ISSUE THREAD

**Issue by Factory-666** [LukeRoss00/gta5-real-mod#329]
Hi, thank you for the ton of hard work you've put into this mod! I love it - made it past the first heist and it is a lot of fun.

One suggestion, is to add the info about setting up the mod in Windows Mixed Reality to the main Readme, and not just in the Release Notes for v7. I didn't find the Release notes at first (I'm new to GitHub) and played for a few hours without the setting. When I finally found the Release Notes and followed them - the stuttering on moving the helmet (Acer WMR) went away and my FPS went up from 40 to 70 on my GTX1070 MaxQ. Still not high enough for comfortable stereo rendering when driving, but it is something!

    **CPU:** i7 7700HQ
    **GPU:** GTX1070 MaxQ
    **VR headset model:** Acer Windows Mixed Reality
    **game version and build:** Epic Games Store, 1.0.2215.0
    **release of the mod:** 7
    **did you follow all the Quick setup steps carefully, in particular step 4?** Yes
    **which settings did you choose (H/M/L) when running the batch file RealConfig.bat?**  L
    **did the batch file report any errors?** No
    **did you change the graphics settings manually?** Yes
    **are you using any other mods?**  Yes, but installed it after Real-Mod. No difference in performance. (Complete Driving Overhaul V-73-1-00)

**Comment by LukeRoss00** [comment]
Great that you're enjoying the mod! There is a comment to that effect in point 6 of the [Quick setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) notes, although I admit it might be easy to miss.

Unfortunately the README already scares some people off due to being too long (one commenter called it dissertation-sized), so I'm reluctant to add even more content to it, especially in the Setup portion that needs to be as light as possible.
