### ISSUE TITLE
Will the OpenXR motion smoothing ever be supported?

### ISSUE THREAD

**Issue by Raging-Beard** [LukeRoss00/gta5-real-mod#331]
With the G2, even on very low settings, it's not a very nice experience, the Vive Pro was much better. Is it possible there will be any improvement or the ability to use the motion smoothing which may help? Thanks.

**Comment by LukeRoss00** [comment]
What do you mean by "not a very nice experience"? I saw from your other thread that you have a 3090, so the experience with the G2 should be almost perfect, and certainly better than the Vive Pro.

**Comment by Raging-Beard** [comment]
Hi, yes it should Hut its like a constant ghosting or permanent reprojection or something.

**Comment by LukeRoss00** [comment]
Did you set `VRAPI = 3` in your `RealVR.ini` file to enable the mod's OpenXR backend?

**Comment by Raging-Beard** [comment]
Yes set to 3 and not using SteamVR at all.

**Comment by LukeRoss00** [comment]
Let's see if the mod log tells us anything interesting. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder: please zip and attach it here.

**Comment by Raging-Beard** [comment]
Please find the log attached. This is with Real Config set to Low, and resolution at 65% on OpenXR (the lowest you can go before distortion). I also have Natural Vision Remastered installed, but it was the same vanilla too.
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6078770/RVRLog.txt)

**Comment by LukeRoss00** [comment]
The log looks fine, there are no errors reported and the VR frame rate is a solid 90 fps. Double check that your Windows Settings> Mixed Reality> Experience Options are set to Best visual quality. Also, render scale should be 100% (not Custom) because the mod doesn't use it, but the forced downsampling might interfere even if there is no visible distortion.

**Comment by Raging-Beard** [comment]
I have discovered something, disabling stereo rendering (numpad 2 in-game) completely fixes the double vision, however everything is then out of scale, things become too big.

**Comment by LukeRoss00** [comment]
At this point, I'm inclined to think that what you're seeing is just the lateral doubling due to alternate eye rendering (https://github.com/LukeRoss00/gta5-real-mod#faq).

There is a very simple test that you can do to be sure: with stereo enabled, and your character on foot, look at a brick wall and turn your head from side to side. If the wall stays still and you see no doubling, ghosting, stuttering or whatever, then your tracking works correctly and the other effects you see (for instance when strafing while looking at the wall) are just due to AER and unavoidable.

**Comment by Raging-Beard** [comment]
Oh, that must be it then! Sorry, I think in the past it performed too bad for me to notice that effect much lol. It's such a shame it can't be avoided while keeping 3D. I can only imagine how good a native VR GTA game would be. Thanks.

**Comment by GorrakTheOriginal** [comment]
I am also on a Reverb G2 and have followed these same steps and resulted to play with stereoscopic rendering off for a lovely smooth experience in lifesize GTA https://www.reddit.com/r/HPReverb/comments/luq9h9/gta_v_5_real_real_mod_vr_with_hp_reverb_g2_2080ti/. 
It is a shame that it has to render the eyes alternatively, but even this way this mod has made a great game out of GTA! Loving in with stereoscopic off, graphics high/ultra and resolution supersampled till there are no pixels underused on the G2 :)
