### ISSUE TITLE
Gamepad not working on Real VR Mod

### ISSUE THREAD

**Issue by teddyted999** [LukeRoss00/gta5-real-mod#333]
Hey how are you?your mod is amazing....I used to play on an Oculus Rift S without too many issues but I just recently purchased an HP Reverb G2 headset and I finally got the headset to function after reading your instructions with the OpenXR etc but now my Xbox controller won't work with the game at all....any advice?I have a 1080 TI OC 11 gigs of VRAM,I7 7700K and 32 gigs of RAM,Windows 10 etc

**Comment by LukeRoss00** [comment]
Hi, thanks! I must say that I have problems too with the Xbox wireless controller when the Windows Mixed Reality app is active: in my case every time the controller rumbles the headset will lose tracking, and often the WMR portal will crash altogether. It doesn't depend on GTA V or my mod either, I see the same behavior in other games.

On my system the problems go away if I connect the controller to the PC with its USB cable and use it controller in wired mode... Worth a try perhaps

**Comment by teddyted999** [comment]
Hey there Luke....thanks for responding:-) I got the game to finally play via the Reverb and xbox controller....and you were absolutely correct,I had to connect the controller to my PC with the USB cable....would loved to play it wirelessly but it's better then nothing lol btw,if you don't mind me asking,how can I learn how to develop VR mods for tradional 2D games?Any advice or can you point me in the right direction?Is proficiency in C++ or # or any other coding needed?You've definately inspired me to learn about game development

**Comment by LukeRoss00** [comment]
Yes, C++ proficiency is definitely needed. Then you'll want to be familiar with at least one graphics API (for instance in the case of GTA V that would be D3D11), and with at least one of the systems used to draw the VR images on the headset screen(s), like the Oculus SDK, or SteamVR/OpenVR, or OpenXR. You'll also need tons of patience and free time, because modding games is mostly an exercise in trial and error, since you usually have no documentation at all available on the workings of the engine ;-)
