### ISSUE TITLE
an exception occurred while executing 'realvr.asi' (0x00007FFB2EC8A2E0),  id 38

### ISSUE THREAD

**Issue by DjsProject** [LukeRoss00/gta5-real-mod#344]
CPU: Ryzen 3 2200g
GPU: NVidia 1060 3gb
VR headset model: Oculus Quest
game version and build: from Epic Games 1.0.2189.0
release of the mod: Release 7
did you follow all the Quick setup steps carefully, in particular, step 4? +
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M
did the batch file report any errors? no
did you change the graphics settings manually? no
are you using any other mods? no

If you attach your RealVR.ini, asiloader.log, and ScriptHookV.log https://mega.nz/file/pkIzFaiD#BQED6cMTl0i1wjOCF-jG1ednG9J2ccMkqeXbIwG1jps

**Comment by LukeRoss00** [comment]
Your logs indicate that you're not using Release 7 of the mod. Older releases no longer work, due to the recent game updates.

I wonder why lately several people have been posting issues, explicitly writing that they're using Release 7 when they actually aren't. Are you guys downloading the mod from some other website?

**Comment by FocusUti1214** [comment]
Does Release 7 and scriphook still with the new 2245 version gta5?

**Comment by LukeRoss00** [comment]
@FocusUti1214 Release 7 works fine with the new updated Script Hook V, if that's what you're asking.
