### ISSUE TITLE
Change scale/fov?

### ISSUE THREAD

**Issue by Raging-Beard** [LukeRoss00/gta5-real-mod#345]
Hi again, with 3d disabled, is there anyway to lower the world scale so everything isn't quite so big please? Thanks.

**Comment by LukeRoss00** [comment]
The world scale and FOV don't change at all going from stereoscopic to monoscopic. The problem stems from an illusion that is created in the brain: since with monoscopic rendering the two eyes get the same image (something that normally occurs only for distant objects), the brain is fooled into thinking that everything is very far away, and so you get a subjective impression that nearby objects, like your hands for instance, are very big and distant instead of being normal size and close.
