### ISSUE TITLE
Low FPS issue

### ISSUE THREAD

**Issue by bandikik** [LukeRoss00/gta5-real-mod#352]
Hello!
First off, thank you very much for the VR mod, looks incredible!

However, I am having an issue with the fps. Everytime I am outside in the city, my fps is around 30 - 60fps. It will only go up to 90 fps when I am in Franklins apartment in the hollywood hills staring directly at a door. If I overlook the city in Franklins apartment, it will also drop down to 35 fps. 

    CPU: Ryzen 5 5600x
    GPU: AMD Radeon 6800
    VR headset model: Quest 2
    game version and build:  v1.0.2189
    release of the mod: Release 7
    did you follow all the Quick setup steps carefully, in particular step 4? Yes, do not have steam version.
    which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H. But have tried all of them now. All have really bad fps. 
    did the batch file report any errors? No
    did you change the graphics settings manually? No
    are you using any other mods? No

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6331615/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6331623/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
This looks a lot like #349, for which sadly we didn't find any solution (yet).

There are several factors in common: inexplicably low frame rate even on Low settings; Ryzen CPU; Radeon graphics card; Quest 2.

In @Loginno's case, since it was the first time I saw the issue reported here, I guessed that it was a problem specific to his system. However, seeing as you have basically the same symptoms, I wonder whether there might be a regression somewhere, in AMD's drivers or in the Oculus runtime, that causes issues with texture and/or geometry streaming, possibly in conjunction with VR.

One big thing that was introduced recently and that might have unexpected side effects is the resizable BAR. By any chance did you guys experiment with it? Unfortunately I don't have access to an AMD-based system at the moment, so I cannot test myself.

**Comment by bandikik** [comment]
Oh yeah, that looks very similar to what i'm experiencing. 

I don't actually have the latest bios on my motherboard to try out SAM but could be worth looking into.

**Comment by Loginno** [comment]
Happy to share anything if you need me to. 
@LukeRoss00 - was not aware of the resizable bar. This got me thinking about a possible action: should we try your version 6? Or a modified version 7 with that feature disabled?

**Comment by Loginno** [comment]
I'll try updating chipset driver to latest version https://www.amd.com/en/support/kb/release-notes/rn-ryzen-chipset-2-13-27-501

**Comment by LukeRoss00** [comment]
@Loginno It's a new feature unlocked by the AMD drivers (https://www.techpowerup.com/279264/amd-brings-smart-access-memory-resizable-bar-support-to-ryzen-3000-series), not anything that I tweak or use in my mod, so reverting to my release 6 will not change anything in that regard (and it's also not possible unless you also downgrade the game).

I was just speculating that the fact that AMD changed such a fundamental aspect of memory management might have something to do with these texture/geometry streaming hiccups that are seemingly popping up.

**Comment by Loginno** [comment]
@bandikik 's CPU is 5000 series, mine is 3000 (Ryzen 5 3600X). According to the AMD article that feature was until now only for the 5000 series. But let's see what a chipset driver update will show.

**Comment by LukeRoss00** [comment]
Would you guys care to generate a full log of the mod on your system? Perhaps by inspecting it I might be able to get some fresh ideas.

To have the mod generate a full log, add a new line `RVRLog = 1` at the end of your `RealVR.ini` and play the game for a few minutes until you get the frame drops, then quit. There will be a new `RVRLog.txt` file in the game folder, which you can zip (it will be quite big) and attach here.

**Comment by Loginno** [comment]
Here you go:
(change .gz to .7z)
[RVRLog.gz](https://github.com/LukeRoss00/gta5-real-mod/files/6337497/RVRLog.gz)

Played 1 mission. Official FPS was 50-72 most of the time I checked.

**Comment by LukeRoss00** [comment]
Thanks for the log! I can see a few interesting things.

First, the average frame rate for the whole run is 64.5 fps, which would be good enough _per se_, but there are brutal spikes in the frame times that fully justify your perception of choppiness. There are a few frames that take more than 50 ms to render, and many that take more than 40 ms. So, first of all it's an objective and measurable phenomenon, where the instantaneous frame rate dips down to ~20-25 fps.

What's even more interesting is where the time is spent, which simply put is, nowhere in the game or the renderer.

When a game is running slow due to insufficient CPU or GPU performance, you will see the various steps in the rendering of the frame each take up more time than they should, adding up to a frame total which is too large to meet vsync.

Instead, in your case, rendering goes on smoothly for most frames (usually completing in ~15 ms, corresponding to ~65 fps), but there are many problematic frames in which everything simply freezes for a long while without anything visible happening. See this example extracted from your log:

```
[RNDR]  50157   780.640580 P+ 0.381ms: curFrameIndex set to  50157[R]
[RNDR]  50157   780.641239 P+ 1.040ms: Unmap() matched the gameplay camera in frame  50157[R]
[GAME]  50157   780.645032 P+ 4.833ms: Update() called
[GAME]  50157   780.645050 P+ 4.850ms: Conflict detected waiting for frame #50157
[RNDR]  50157   780.648985 P+ 8.786ms: Unmap() fixed up the really close gameplay camera {yaw = -129.65, pitch = 3.72, roll = 4.86}[R] for frame  50157[R]
[WAIT]  50157   780.650100 P+ 9.901ms: Ready to begin frame #50157 (wait time = 26.1 ms, max = 54.9 ms)
[WAIT]  50157   780.650106 P+ 9.907ms: RVR predicted time 780.693630 for future frame #50157: corrected to 780.707519 for #50158
[GAME]  50157   780.650108 P+ 9.908ms: Predicted head pose {yaw =  -18.97, pitch =  -1.78, roll =    2.07; pos = ( 0.060, -0.005,  0.060)} should be used for frame  50158[L]
[WAIT]  50157   780.650109 P+ 9.910ms: Waiting to begin frame #50158
[GAME]  50157   780.650141 P+ 9.942ms: World rotation set to {yaw = 52.07, pitch = 0.00, roll = 0.00} (tracking gameplay camera)
[GAME]  50157   780.650894 P+10.694ms: AdjustViewInverse() fixed the gameplay camera to {yaw = 123.10, pitch = -1.78, roll = -2.07; pos = (-1063.008, -1288.907, 7.700)}[L] and set nextFrameIndex to  50158[L]
[RNDR]  50157   780.651672 P+11.473ms: TrackProj() called with zoom = 0.7813
[RNDR]  50157   780.681887 P+41.688ms: Beginning frame #50157
[RNDR]  50157   780.681908 P+41.709ms: Committing eye [R]
[RNDR]  50157   780.681933 P+41.734ms: Committing HUD
[RNDR]  50157   780.681937 P+41.738ms: Submitting frame #50157: sampletime = 780.612771, displaytime = 780.707519, [L] pose is {yaw =  -19.06, pitch =  -1.81, roll =    2.08; pos = ( 0.031, -0.006,  0.050)}, [R] pose is {yaw =  -19.00, pitch =  -1.79, roll =    2.07; pos = ( 0.090, -0.003,  0.070)}
[RNDR]  50157   780.682155 P+41.956ms: Submitted frame #50157, gathered 2 frame stats; GpuPerfScale = 1.00, ASW not available
                                         HmdVsyncIndex=56054 AppFrameIndex=50108 AppDroppedFrameCount=5952 AppMotionToPhotonLatency=80.359ms AppQueueAheadTime=16.742ms  AppCpuElapsedTime=0.276ms AppGpuElapsedTime=0.132ms CompositorFrameIndex=55922 CompositorDroppedFrameCount=0 CompositorLatency=38.483ms CompositorCpuElapsedTime=1.062ms CompositorGpuElapsedTime=0.674ms CompositorCpuStartToGpuEndElapsedTime=0.991ms CompositorGpuEndToVsyncElapsedTime=9.817ms AswIsActive=0 AswActivatedToggleCount=0 AswPresentedFrameCount=34 AswFailedFrameCount=6
                                         HmdVsyncIndex=56055 AppFrameIndex=50108 AppDroppedFrameCount=5953 AppMotionToPhotonLatency=94.280ms AppQueueAheadTime=16.742ms  AppCpuElapsedTime=0.276ms AppGpuElapsedTime=0.132ms CompositorFrameIndex=55923 CompositorDroppedFrameCount=0 CompositorLatency=38.482ms CompositorCpuElapsedTime=1.120ms CompositorGpuElapsedTime=0.689ms CompositorCpuStartToGpuEndElapsedTime=1.020ms CompositorGpuEndToVsyncElapsedTime=9.784ms AswIsActive=0 AswActivatedToggleCount=0 AswPresentedFrameCount=34 AswFailedFrameCount=6
```

Everything appears to go smoothly up to the 11.473 ms mark, then suddenly and for no apparent reason the rendering thread seizes up for more than 30 ms (!) without anything else happening in the meantime.

Now, if no other thread apart from the rendering thread ever got stuck, that might be explained away with the GPU sometimes stalling (due for example to a texture resource which is not yet ready). But in other frames I see other threads getting the same treatment. That almost invariably points to a hardware problem, or a faulty driver. Since there is now two of you having more or less the same problem, I would tend to exclude a hardware issue and conclude that there is something seriously wrong with the drivers.

Pointing out specifically which driver (CPU, chipset, video card, ...) is causing the freezes would require a much more in-depth analysis that we cannot realistically carry out for a game mod.

**Comment by LukeRoss00** [comment]
Did I scare you guys away? :-D

**Comment by Loginno** [comment]
Heck no. I'm with you until this gets solved one way or the other!
But I don't really see what can be done other than throwing AMD away and using Intel and Nvidia...

**Comment by LukeRoss00** [comment]
Depends on how much time/money you're willing to throw at the problem :-P

Certainly most VR gamers stick to NVIDIA. They tend to have a better reputation in terms of drivers quality.

You might want to analyze your system with [LatencyMon](https://www.resplendence.com/latencymon), especially while playing the game, to see if anything revealing shows up...

**Comment by LukeRoss00** [comment]
Closing the issue for inactivity, feel free to reopen if you have any new information.
