### ISSUE TITLE
WMR for Steam update specifically mentions this mod...

### ISSUE THREAD

**Issue by Raging-Beard** [LukeRoss00/gta5-real-mod#359]
"Adds support for titles that submit frames using alternate poses (e.g. GTA V R.E.A.L. mod)." Direct quote from patch notes.

I thought I would see how this ran now in SteamVR with my G2, so set API to OpenVR. Loading screens are all good in VR, but once in game, I only see minimap and menus, everything else is black but shows fine on monitor. I have the latest Scripthook, and reverting back to OpenXR without SteamVR it works fine.

Firstly, any idea what that issues is please?

Secondly,  what should we expect this update to do? I am pretty sure I had it run on SteamVR before (maybe this added support broke it?), should it look better as in apparent less ghosting on lateral movement, or allow for motion smoothing etc?

Thanks.

**Comment by LukeRoss00** [comment]
It's great that they are still working to make their SteamVR driver compatible with AER! I will try to test it next week.

However, I still advise using the OpenXR backend with WMR headsets like the Reverb G2, and so does Microsoft:

![image](https://user-images.githubusercontent.com/34809409/117415892-1b2e6280-af19-11eb-8060-1d1642580f4a.png)

**Comment by LukeRoss00** [comment]
I (very briefly) tried the beta update and can confirm the black screen issue. The runtime doesn't report any errors, but the eye layer turns out all black. The overlay layer works though, which explains the menus and HUD being visible.

Until Microsoft or Valve get this sorted out, my advice stands: keep using the OpenXR backend for WMR headsets.
