### ISSUE TITLE
Alternative to alternate-eye rendering

### ISSUE THREAD

**Issue by Dan88Man** [LukeRoss00/gta5-real-mod#360]
Not sure if this is a stupid comment, but I would like to mention that I used to play GTA 5 in 3D (non VR, but side-by-side 3D) with the tool Tridef3D ignition (discontinued unfortunatelly) and it didn't use the alternate-eye rendering method. At least that's what I believe, since movements are very smooth with this tool with no ghosting.

@LukeRoss00, have you heard of this tool? Maybe it is worth looking deeper into it to figure out if the system this tool uses can be used to achieve the stereoscopic view in your mod?

Apart from this suggestion, is there any chance that the ghosting caused by the alternate-eye rendering will ever be solved? I personally don't dare yet starting a full game session from start to finish before this issue isn't solved. I think, if this was solved, it would make this game one of the best VR titles in existence. But with this issue I can't fully enjoy it in longer sessions unfortunately. Thanks anyway for this incredible work!

Cheers

**Comment by LukeRoss00** [comment]
To achieve zero ghosting, you need to draw exactly one frame for each screen refresh. With side-by-side 3D (which incidentally is typically half-resolution) that means 60 full frames per second. In VR, with a headset refresh of 90 Hz, you'd need 180 full frames per second, and the resolution must be much higher due to the magnifying effect where the screen surface is brought to fill your entire field of view.

There is no way of squeezing 180 fps from GTA V with current systems. I recently benchmarked it with an RTX 3090, and the maximum I could see was 140 fps, with frequent drops around 110 fps depending on where the camera is looking, _and_ with antialiasing off. The problem is aggravated by the fact that GTA V was not built to fully utilize many-core CPUs, so at extremely high frame rates the game is no longer GPU bound.

So no, this issue cannot be "solved" for the moment. Perhaps with PCs from the future, if the Great Chip Shortage ever relents :-)

**Comment by Dan88Man** [comment]
Thanks for getting back.
What I meant was that perhaps the 3D effect isn't achieved by alternate frame rendering in the Tridef3D software, but instead by 2 actual camera views.

Isn't the fact that both frames are showing up in the screenshot, if I take a screenshot using Tridef3D, an indicator for both cameras being rendered at the same time?

Screenshot:
![](https://i.imgur.com/AjFpiWR.png)

So I was wondering if this method which Tridef3D uses (I dont know how it is called or how it works) can be used for the VR mod as well for achieving the 3D effect.

There is a bit of warping around the edges of near objects. But I find those more acceptable than the impression of a low frame rate which is caused by the alternate frame rending.

**Comment by LukeRoss00** [comment]
Ha okay, you're talking about so-called "fake 3D" or depth-buffer-based 3D reconstruction. I'm sorry but I won't use it in my mods, it just doesn't look R.E.A.L. enough to me!

Puns aside, the truth is that fake 3D avoids most of the performance hit of true 3D, but it only works for objects whose virtual depth is "inside" the screen, i.e., it has no pop-out. In VR, where there is no actual screen and objects and characters get super close to your face, fake 3D just doesn't cut it. To my professional eye at least, it basically looks like monoscopic with artefacts.

Speaking of which, have you tried monoscopic mode with GTA V?

**Comment by Dan88Man** [comment]
Ok, I understand. Maybe it is indeed not the right method for VR. For me though, it looks way better than just monoscopic with 3D artefacts, at least on a proper 3D screen with shutter glasses. But I don't know how it looks in VR and I can somehow understand why it might not work very well with VR. Is it the method which VorpX is doing? If yes, I am not a fan of that either. But again, on a 3D screen (with Tridef3D) it looks pretty good, so I am not entirely sure if we are talking about the same method.

I haven't tried monoscopic with GTA 5, but after you suggested it, I tried it in Red Dead Redemption 2. It is nice and better than I expected (better than every 360 VR video), but it is not my cup of tea for a long gaming session. Maybe if I increase the resolution. Should try that.

Btw, congratulations to your successful Patreon page. I hope that this remains sustainable for a long time so you can work on further mods. You already mentioned some potential candidates for the future. Question regarding that: Is you being forced to use this "alternate frame rendering" method only something specific for the Rockstar engine, or is it to be expected that the 3D effect needs to be done the same way on other titles? Or is there a chance that on other titles you will be able to set true 2 cameras at the same time and not have those ghostings?

Cheers

**Comment by LukeRoss00** [comment]
VorpX calls depth-buffer based reconstruction "Z3D", and yes, if I'm not mistaken it's the only method it has available for RDR2 and DX12 titles in general.

In my opinion, alternate frame rendering is the only viable technique to mod true stereoscopic 3D into GPU-intensive games, like all AAA titles that came out recently. The problem is not the engine but how many full-resolution frames the GPU has to draw each second. Only very old games (like Quake, Doom 3, etc.) can be modded to run at 180 fps in ~4K resolutions on current hardware.

**Comment by Dan88Man** [comment]
So are you saying, that you COULD place TWO cameras at the same time in some games, but you wouldn't do it because of the performance issue and rather use alternate frame rendering instead?

**Comment by cercata** [comment]
With normal 2 eye rendering, I guess ASW and other frame interpolators could be used, and maybe that would be less disturbing for some users. I have hear several people they can't hold the alternate eye rendering thing.

**Comment by LukeRoss00** [comment]
What you guys propose is feasible only with Single-Pass Stereo (https://developer.nvidia.com/vrworks/graphics/singlepassstereo), and the game engine must be built around it.

**Comment by LukeRoss00** [comment]
Additionally, even Single-Pass Stereo (also called Multiview rendering) is not miraculous. The pixels still need to be shaded for each view. For RDR2, a game that at VR resolutions is completely GPU-bound, the frame rate would probably be about 55% of what I get with alternate eye rendering, so it makes no sense to invest the couple of man-years needed to adapt the engine to Multiview

**Comment by cercata** [comment]
2 man years ? :-O
Not worth it even if performance was not a problem

**Comment by dipaw** [comment]
Perhaps off topic, but close. Virtual Desktop recently released an SSW that takes 45 frames to extrapolate to 90.
Is there a chance the mod will ever be VD compatible?

**Comment by LukeRoss00** [comment]
Only if Guy Godin is willing to take another stab at making his program support independent eye poses correctly. I worked with him in the past, but he didn't seem to want to invest much time in the issue and he hit some limitations in the Oculus mobile SDK
