### ISSUE TITLE
Can automatic recentering be disabled?

### ISSUE THREAD

**Issue by ideka** [LukeRoss00/gta5-real-mod#384]
It seems that, 9 times out of 10 when I have to recenter the camera, it’s because the mod automatically recentered it earlier at a time when I happened to be looking to the side.

For example I have to make sure to look straight ahead when getting in or out of a vehicle or I know for a fact my view will get messed up.

Any help would be appreciated.

**Comment by LukeRoss00** [comment]
Unfortunately not. When transitioning from walking to driving, the game always resets the camera to the direction the vehicle is facing. In VR there is no guarantee of course that the vehicle will be aligned with the direction the user is looking at, so the only acceptable solution to avoid the camera pointing at seemingly random angles every time you enter a car is for me to recenter, which basically realigns the world so that the car is actually pointing in the direction you're looking.

**Comment by ideka** [comment]
So it sounds like you're saying disabling it would make it worse. Well if we know that for a fact then I guess it can't be helped, feel free to just close the issue in that case.
