### ISSUE TITLE
Tennis court world slightly tilted upwards. 

### ISSUE THREAD

**Issue by QUAKEULUS** [LukeRoss00/gta5-real-mod#395]
Using the static camera, and resetting the view, the ground still seems to be tilted upwards from camera's perspective.

On a related note, I don't see a difference between "NUMPAD 3    Toggle darts/tennis FOV override - on at start"

**Comment by LukeRoss00** [comment]
Yes, the tennis cameras are preset by the game to look at the court and as such don't preserve the horizon alignment. However I find it's better this way rather than having to play with your neck craned down all the time!

The difference is visible only if you disable the universal FOV fix (which is not recommended).
