### ISSUE TITLE
GTA 5 mod no longer works

### ISSUE THREAD

**Issue by itsmeniggy** [LukeRoss00/gta5-real-mod#42]
the vr mod doesn't work anymore.....keeps saying there's a problem with scripthookV

**Comment by LukeRoss00** [comment]
Yes, that's normal: all the ScriptHookV-based mods are broken now because the game has been modified due to the Diamond Casino Heist update. The game version has been bumped to 1.0.1868.0.

Alexander Blade (the author of Script Hook) usually needs a few days to make it compatible with new game versions: check his page at http://www.dev-c.com/gtav/scripthookv/ to see when a new release comes out.

**Comment by naji2004** [comment]
This mod is pure Magic it came to us as an early X-mass gift Thank you very much  @LukeRoss00  . it was so addictive that I stop playing all my other games and restart playing GTA V from the beginning. wish the script hook update comes sooner.  some might call me a dreamer but I really believe that there is a possibility of cloning and working on the same  VR mod for Red Dead Redemption 2!!! a mod I can support and contribute funds to through a Patreon page now that will be BIG.

**Comment by LukeRoss00** [comment]
Alexander Blade has already updated Script Hook V; you can go to http://www.dev-c.com/gtav/scripthookv/ and download the new zip file. From that, extract `ScriptHookV.dll` into the GTA V folder. Be careful not to put it into a \bin subfolder; it should be at the same level as `GTA5.exe` and replace the old one.

I just tested it very briefly and it appears to me that all is working again. I'll leave this issue open anyway so people who might be unfamiliar with the Script Hook update routine know what to do.

**Comment by LukeRoss00** [comment]
Closing this because the [new release](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r2) supports version 1.0.1868.0
