### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by Marshallcoolman** [LukeRoss00/gta5-real-mod#420]
I am getting less than 40 FPS on i5 2400 and GTX 1050 ti, i am also medium settings is that normal for my specs or can i somehow boost it?

**Comment by LukeRoss00** [comment]
That sounds about right for a 1050. You can double check by installing MSI Afterburner and using its integrated RivaTuner to monitor your GPU usage (Task Manager doesn't give reliable figures with my mods). If your GPU usage is around 95-100%, there's nothing you can do other than lowering the graphics options and the Resolution Scale further

**Comment by Marshallcoolman** [comment]
My GPU plays 99% of other VR games with no issues. I have tried HL: ALyx, Boneworks, Superhot, Beat Saber all with no issues

**Comment by LukeRoss00** [comment]
That's not really relevant though, because none of those games are open world and have complex graphics like GTA V (HL:A looks very good, but the Source engine is much lighter than the Rage engine).

If you suspect that the mod is impairing your fps, which I can assure you it doesn't, there are a couple of checks you can perform: remove all the mod files, then either run the game without changing the resolution and graphics settings from what the mod configured with the medium preset that you selected, or reset your graphics settings and run the game in 4K (3840x2160) which is roughly equivalent to the 2700x2700 resolution that the medium preset uses.
