### ISSUE TITLE
Gta v vr broke my game 

### ISSUE THREAD

**Issue by timmyboi420** [LukeRoss00/gta5-real-mod#421]
I delete the mod reinstalled my game but when I play it uses my gpu memory so much and always goes to 75hz and 1280 something how do I fix my game it’s at like 4700 mb used when before it was 2700 my game is broken please help

**Comment by LukeRoss00** [comment]
There is never a need to reinstall in order to remove the mod. It is sufficient to delete the files that were extracted from the .rar archive.

Anyway, your problem is not the game folder but the graphics settings. You're probably still using the settings optimized for VR. Before running the game next time, go to the `Documents\Rockstar Games\GTA V` folder, delete the `settings.xml` file, and rename `settings_ori.xml` (the backup file that the mod saved during installation) to `settings.xml`, then you'll be good to go.
