### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by uyizz** [LukeRoss00/gta5-real-mod#436]
it says  unknown game version what do i do

**Comment by LukeRoss00** [comment]
See #239

**Comment by uyizz** [comment]
is that all u needed

**Comment by uyizz** [comment]
I read it and I have done everything

**Comment by LukeRoss00** [comment]
*3a. Since Rockstar keeps updating the game, each time breaking all script mods, you should also download the latest Script Hook V package from Alexander Blade's page (http://www.dev-c.com/gtav/scripthookv/) and use it to update the `ScriptHookV.dll` file that you have in the game folder; the other files in `ScriptHookV_1.0.XXXX.Y.zip` are unchanged and you don't need to replace them.*

**Comment by uyizz** [comment]
i did

**Comment by LukeRoss00** [comment]
You probably extracted the `ScriptHookV.dll` file into a `bin` subfolder instead of updating the one that's in the executable folder. The "Unknown game version" error is always caused by an old Script Hook V

**Comment by LukeRoss00** [comment]
Also, "1.0.0.40" is the version of the launcher, not the game's

**Comment by uyizz** [comment]
yeah u messed up my pc mod gave me a virus i deleted everything and game worked fine was acc hoping this worked

**Comment by LukeRoss00** [comment]
What are you talking about? The mod works perfectly for thousand of users, and virus scan is perfectly clean: https://www.virustotal.com/gui/url/da35b694e89650e5893cf4598cc42b312792338ed6fee89efb141f3562a170dc

If you want to make it work on your system I can help you, but don't go throwing around unjustified accusations
