### ISSUE TITLE
major jaggies and aliasing even beyond high settings

### ISSUE THREAD

**Issue by ragesaq** [LukeRoss00/gta5-real-mod#47]
Specs
9900k+2080ti
Valve Index
3440x1440 monitor

I started trying this mod out last night and while it mostly works great, there's a few significant issues. One of which is the high level of edge aliasing and jaggies due to no AA. I would like to improve visual quality since even at beyond high settings the performance is very high.

I've tried changing the resolution to 1440x1440 but I get issues where the desktop window tries to snap to fullscreen like its running in desktop mode and the VR mode is broken. I verified by replacing the file and changing the resolution as the only change, no luck.

I was able to successfully use 1200x1200 which changed the menu UI, but introduced black bars on the sides of cutscenes and did not appreciably improve edge aliasing

Here is a clip from my broadcasting I did of it where you can see tons of aliasing all over the place, its a bit jarring.

https://clips.twitch.tv/OpenPrettiestNarwhalPeanutButterJellyTime
Here is a clip I did of the black bars that show up during cutscenes
https://clips.twitch.tv/NimbleObliquePorpoiseShazBotstix

**Comment by LukeRoss00** [comment]
Okay. As you can see by comparing your videos to others of people who are using the mod, there is definitely something wrong with your configuration. You shouldn't have any black bars during cutscenes, and the huge aliasing you get suggests that the game is not using the correct resolution/frame scaling. See for instance [this](https://www.youtube.com/watch?v=V_y8gcmre8I) video by Nathie for an example of how the mod should look.

Please attach your `Documents\Rockstar Games\GTA V\settings.xml` to your reply and we'll try to work out what's wrong!

**Comment by ragesaq** [comment]
So one weird thing that seems to keep happening is the settings.xml gets reset back to desktop resolution settings after saving and quitting, so I can't provide you what I used in the clips.
I wonder if my 21:9 monitor is causing issues? Are there other places that try to automatically optimize the game settings that could be causing an issue? I have nvidia geforce experience uninstalled and nothing else that should mess with anything.

The black bars don't show  up when I use your provided 1080x1080 high settings, but when I change *only the resolution* the bars start showing up. 

Also, the perspective of cutscenes is often *extremely* jacked up to the point where I can hardly make out what is happening, and if I didn't have iron VR legs I probably would get sick from how jacked up it is. I wonder if the separation value needs to be adjusted to half my IPD? I have a 70mm IPD and I notice the settings appear to be set for a 62mm IPD if I am deducting the purpose of the separation value.

**Comment by LukeRoss00** [comment]
Did you follow all the instructions detailed in the [Quick Setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) initial part of the README? What you describe often happens to people who omit editing in their videocard description, or mess with the graphics options in-game instead of editing them in the file. GTA V **never** overwrites your settings file unless you change the graphics options while playing or it detects a videocard name mismatch.

**Comment by ragesaq** [comment]
Gah, I did do that the first time, but I messed everything up by enabling MSAA and when recovering the files I forgot to put my graphics card settings in. Fixing that...

Thoughts on how messed up cutscenes look and/or the separation settings?

**Comment by LukeRoss00** [comment]
The answers to all your questions are in the README. Please read it.

**Comment by virtualmisterl** [comment]
@LukeRoss00 
I have been getting the same antialiasing shimmering & was wondering if my settings are ok.

I think Maybe there is a problem with my settings file also.
I'll explain.
When I went in to change my settings xml, my graphics card said gtx 1080ti.
I'm using an rtx 2080ti so that's what I changed it to instead.
As the game ran, looked pretty good & I had a frame rate nearly always 90+ I presumed it worked.

I have an odd setup though.
I had a 1080ti when I originally installed gtav but upgraded to a 2080ti.
I have a water loop in my pc & ended up keeping both in there for comparison purposes.
The 1080ti sits unused in 2nd slot.

Also I moved gtav to my 2nd hard drive some time ago but the settings xml is located on my primary ssd.

Is it possible I need to start a fresh & somehow get my original xml file to show rtx 2080 ti before I install the mod?
