### ISSUE TITLE
Pretty intense jagged edges

### ISSUE THREAD

**Issue by Nicksonman** [LukeRoss00/gta5-real-mod#52]
Happens regardless of resolution. The mod needs an MSAA equivalent to iron out the jaggies which are worse in the distance compared to the foreground, but still quite bad overall. Objects in the distance such as buildings and traffic often look like jelly. The cutscenes on the other hand look very sharp and crisp.

Valve Index
1080ti
i7 4790k
32gb ram

**Comment by LukeRoss00** [comment]
The fact that your jaggies don't seem to depend on resolution is very strange. Please download [this](https://github.com/LukeRoss00/gta5-real-mod/files/4012378/d3d11_log.zip) version with logging enabled and decompress it so that it overwrites the old d3d11.dll file in the GTA V folder.

Put on your headset, run the game and let it finish loading, up to the point where you gain control of your character; then quit the game. You should find that the mod has created a new log file named RVRLog.txt in the GTA V folder: the file should be around 10 MB in size. Zip it and attach it here to your comment, so that I can take a look and see whether I can find the problem.

**Comment by Nicksonman** [comment]
There is a definitely an improvement in jaggies when going up in resolution, but even at my max (1080x1080) the jaggies are still pretty intense. Thanks for checking this out!

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4013696/RVRLog.txt)

**Comment by LukeRoss00** [comment]
I will examine your log as soon as I can. In the meantime, please have a look at [this video](https://www.youtube.com/watch?v=hbRPts3SzY0) by Hoshi82. Watch it in fullscreen, and you will get a very good idea of how the mod should look in the headset. Of course there are YouTube compression artifacts mixed in, but especially when the action is slow I find that the video gives a pretty close approximation to the actual look of the mod in VR.

If you have worse jaggies than are visible in the video, there is definitely something wrong with your config.

**Comment by Nicksonman** [comment]
Played the video at 720p60. Wow, is that really the quality he gets in the
headset? Mine is far worse. I wonder what res he has the game at.

**Comment by LukeRoss00** [comment]
Does the video not play at 1080p60 for you? Yes, that's the quality that everybody gets with a powerful video card, and you should be able to get it too. What version of SteamVR are you on, and what is your setting for Render Resolution in SteamVR?

**Comment by Nicksonman** [comment]
Was watching the video on my phone, but I watched it again at 1080p60 on a monitor and my opinion remains the same - it's a lot better than what I'm getting in the headset. 
Not sure about my SteamVR version but it's definitely the latest - I'll get a version number out to you soon.
By Render Resolution do you mean my super sampling setting?

**Comment by LukeRoss00** [comment]
> By Render Resolution do you mean my super sampling setting?

Yes, but if you have the latest SteamVR version, it should be called [Render Resolution](https://steamcommunity.com/games/250820/announcements/detail/3150762393108758897)

**Comment by Nicksonman** [comment]
I'll check this out. I normally adjust my super sampling setting in Open VR Advanced Settings rather than directly in Steam. The thing is, at least on my system, it doesn't affect all games and unfortunately GTA V is one that it doesn't work on. 
What's strange is that adjusting my super sampling setting in Open VR Advanced Settings has **always** worked in a SteamVR Home Environment but lately it hasn't been. I'll check this out directly in Steam.

**Comment by LukeRoss00** [comment]
My suggestion is to put it on Custom (**not** Auto) and set the slider to some value greater than or equal to 100%. While the mod will ignore the setting, because it employs a different mechanism for supersampling, if SteamVR "Auto" heuristics gets confused by the alternate eye rendering and decides that your GPU is not keeping up, it might bring the render resolution down to below 100%, and that will definitely impact your in-headset resolution.

**Comment by Nicksonman** [comment]
Sounds promising, will keep you in the loop. Also, I might try and record some video in the headset (using a phone camera) and see what it will show.

**Comment by Nicksonman** [comment]
STEAMVR 1.9.16 

Now let's see if this custom setting does anything.

**Comment by Nicksonman** [comment]
Just checked. It's been on these settings the whole time.
![vr-settings](https://user-images.githubusercontent.com/44262794/71711515-8fed1a80-2e55-11ea-8e90-93b93150a757.JPG)

**Comment by Nicksonman** [comment]
I recorded a direct video with my phone, unfortunately it doesn't look too bad on my phone so no point in showing it to you.

**Comment by Nicksonman** [comment]
It's the same setting that I use here but for some reason it no longer affects my games, it's like the slider is disabled. Weird.

![opvras](https://user-images.githubusercontent.com/44262794/71712320-db54f800-2e58-11ea-9dc7-56746115e37c.JPG)

**Comment by LukeRoss00** [comment]
> I recorded a direct video with my phone, unfortunately it doesn't look too bad on my phone so no point in showing it to you.

Well, I don't know what to say to that. As for your log file, the only weird thing that it shows is that you're running GTA V with a frame scaling of 2/1 (`<SamplingMode value="8" />`), despite you posting on Reddit that you were using the high settings template which has 5/2 (`<SamplingMode value="8" />`) instead. So your framebuffer is 2160x2160 instead of 2700x2700.

**Comment by Nicksonman** [comment]
The log file I sent you was for the low settings. I'll send one for the
high settings too.

**Comment by Nicksonman** [comment]
And here is my log using the high settings file. Cheers. 

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4021543/RVRLog.txt)

**Comment by LukeRoss00** [comment]
Closing this issue as the new release fully supports MSAA, FXAA and TXAA
