### ISSUE TITLE
double vision/eyes not syncing up when turning car or head

### ISSUE THREAD

**Issue by yoda123456** [LukeRoss00/gta5-real-mod#53]
Yo this mod is amazing been waiting for something like it for years, **so I'm not sure if this is normal but whenever I move to camera with controller i see double this applies to almost anything moving vertically across the screen not sure if this is a bug, just me, or if it's just this way*** also not sure if it's the jittery issue people are reporting or if it's something totally new thus this new issue topic, thanks in advance for any help!

**Comment by yoda123456** [comment]
Also worth noting it doesn't happen in monoscopic mode, everything is installed correctly, And I'm playing with no other mods on a 1080 ti.

**Comment by LukeRoss00** [comment]
What you describe is not the jittering issue that WMR headsets have, but just the normal artifacts caused by alternate eye rendering (I assume that you actually mean "moving horizontally across the screen", not vertically). If the world looks stable when you rotate your head without touching your controller, than you're using the mod correctly.

**Comment by yoda123456** [comment]
*So I'm assuming it's not it's probably not fixable then*? Also once again wasn't sure if it was a current issue or a known one hence the cross post

**Comment by LukeRoss00** [comment]
It's just the way alternate eye rendering works. And it's the very first FAQ entry in the README.
