### ISSUE TITLE
[GTA 5 Redux] Game play on a rectangular surface 

### ISSUE THREAD

**Issue by Li0n-0** [LukeRoss00/gta5-real-mod#61]
I mention it here as you wrote in your read-me that you support GTA5 Redux. If this is no longer the case please delete this issue.

My config:
Valve Index
intel i7 6700k @ 4.5 gHz
Amd Vega 64
16 GB Ram

R.E.A.L release 4
GTA5 Redux v1.8

no other mod, beside OpenIV

I follow the instruction for both mods.

The game run fine with only R.E.A.L installed but with GTA5 Redux added it plays on a rectangular surface, loading screen and actual game. The head-tracking is still working.
Objects also appear double, like a stereoscopic image on a 2D screen.

If you need any other testing, sending log, I'll gladly help you.
Thanks for the amazing work you put into this.

**Comment by LukeRoss00** [comment]
Thanks for providing full details! I see that you're using an AMD card. The problem _might_ be there, as Redux changes some of the shaders used by the game, and I can only test it on NVIDIA cards.

Did you enable the mods folder? If so, please try renaming it to something else (like "modz") so that Redux will be disabled, then run the game to check whether my mod works normally again (that way we can be use that the problem is reproducible and not simply something that went wrong e.g. with Redux installation). If everything works fine with Redux disabled, please enable it again by renaming the modz folder to mods and try switching to 3rd person (users of the previous release wrote that Redux was already working but only in 3rd person).

**Comment by Li0n-0** [comment]
I tried with the mods folder renaming, works fine as expected.

Tried again with REAL + Redux, same rectangular surface, go to third person: whoa :D
So you were right, redux do strange stuff with first person but works wonder in third.

Seems like a complicated thing to solve I guess...
unless...

You die ! 

Get killed, wait for the cinematic to finish, and tadaa ! REAL + Redux now works fine in first person, both on foot and in a vehicle.

The game did crash after about 10min so maybe not that fine. But I haven't tested it long enough to know where it's from.

I hope this information can help you to improve the support for Redux but I'm fine with the workaround (wake up with a grenade :D )

**Comment by LukeRoss00** [comment]
Hahaha, that's insane! But more or less what I would expect from Redux, it's a mod that messes a lot with the inner workings of the game, and not always in a good way. Several modders that I respect also say that Redux is basically stolen work, so I won't really go out of my way to make it stable in VR :-/

As I said elsewhere, my personal preference goes to M.V.G.A.!

**Comment by Li0n-0** [comment]
Another fun facts of programming ;)

I understand your position, I've never used Redux before today and didn't know about the "political" stuff , but it seemed to be a nice all-in-one package.

I'll try M.V.G.A. and Natural Vision too, thanks for the suggestion. And again thanks for this mod.

**Comment by Li0n-0** [comment]
Response to edit : yes I did, also try entering/exiting car with different camera. Don't work

You need to die !
;)

**Comment by LukeRoss00** [comment]
I cannot reproduce the issue, so for the moment I'd wait to update the README until somebody else chimes in and we find out more about the cause (video card? something else altogether?)

**Comment by trillex** [comment]
I have the same issue but with a nvidia card (I replied to your thread on reddit). 

I'm also using OpenIV with mod directory and, just for fun, I tried it without mod directory as well - same thing.  

Specs are: 

i7 8700k
2070 Super
Valve Index

Reason I want to play Redux is due to the gameplay changes since mods that change similar things are severly outdated (GTA 5 Realism etc.). But I'll give M.V.G.A. a go.

**Comment by LukeRoss00** [comment]
Quick idea: could you try setting Post FX to Normal?

**Comment by trillex** [comment]
That works for me! :)

**Comment by trillex** [comment]
Scratch that, it worked until the first loading screen. Curiously, it is full VR in cutscenes but as soon as it snaps out of it, it is the rectangular surface once again. Changing Post FX while in-game did not put it back to normal, either.

**Comment by LukeRoss00** [comment]
Does the dying trick work for you?

**Comment by trillex** [comment]
Sadly not

**Comment by LukeRoss00** [comment]
Are you guys both using the High settings preset?

**Comment by trillex** [comment]
Ah, yes - I keep forgetting the real information. Yes, I'm using high, everything else completely default save the post fx set to normal now.

**Comment by Li0n-0** [comment]
Medium for me. Haven't try the other.

**Comment by LukeRoss00** [comment]
Okay, I finally managed to repro the issue. It appears to be very random: changing graphics settings, time of day, replaying missions, etc., at some point the issue you guys described started and later, in similarly random manner, it disappeared. I also saw another problem where cutscenes became horribly fuzzy. I have to say that I'm already thinking of dropping support for Redux as it looks like a messy bugfest (I had found other annoying gameplay issues in the past, although not so showstopping) and I really don't want to be dragged into spending a lot of time to make a mostly stolen frankenmod work.

Anyway, from my experiments now the common pattern that I found is that the issue seems to go away if some form of antialiasing is enabled (FXAA or MSAA). YMMV.

**Comment by trillex** [comment]
I honestly only tried out Redux as you listed support for it. I've installed MVGA instead and will give it a proper replay soon. :)

**Comment by LukeRoss00** [comment]
Yeah sorry, my rant wasn't in any way meant to rebuke you!

**Comment by trillex** [comment]
Oh, no, wasn't that - it's a good idea to remove it as fixing it could probably be a nightmare in its own and not all that important, the VR in of itself is amazing enough.

**Comment by LukeRoss00** [comment]
> Edit: can't try the postFx now, will update tomorrow.

When you have time, could you also try enabling any form of antialiasing?

**Comment by Li0n-0** [comment]
Little more testing:

- Enable PostFx: didn't test, I play the game in french and none of the translation sound like PostFx...

- Enable anti-aliasing: tried FXAA, worked, on exiting the menu the "real" vr was back. Didn't try the other type of anti-aliasing

- More try of the dying workaround: seems to work only when it's night (ie if it's daylight when you exit the hospital)

- Going to bed seems to fix it too, haven't tried enough to be sure but I guess same rule as dying, you must wake-up during daylight.

- So daylight workaround it is: saving the game during daylight, in first person. Close it. Launch it. It now plays well in vr, in first person, from the start.

- Last try I did: back to first step, save the game at night, in first person. Close it. Launch it. (shouldn't work right ?) it works...

So yes, unreliable behavior. (too bad I liked my dying workaround ;))

@LukeRoss00 I really appreciate you take to time to answer and tinker about this issue but I'm in the same position as trillex, I just download Redux because you listed it as compatible and it looked cool. I have no tie to it and don't really regret uninstall it if you decide to drop support for it. I'll try one of the beautification mod you listed previously, or not at all, just playing GTA in REAL vr is awesome on its own.

**Comment by LukeRoss00** [comment]
Post FX is the 6th option from the bottom, just before the Motion Blur Strength slider: ![image](https://user-images.githubusercontent.com/34809409/73590525-b7caaf00-44e3-11ea-9b7d-bb6c1e5c9f96.png). From my experiments it should be set to its minimum value (Normal in English) otherwise cutscenes will become fuzzy.

Thank you for the careful analysis!! I guess though that saving during daylight is not a definitive solution, because the problem will reappear as soon as night falls :-)

**Comment by LukeRoss00** [comment]
I've updated the [README](https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking) with the information that we discovered.

**Comment by Li0n-0** [comment]
Thanks, it's called "Qualité effet visuel" in french, "visual effect quality" will be a literal translation.

I try every settings for it, without any anti-aliasing, at night. It didn't change a thing, game display on a rectangle.
For my case the most reliable solution seems to enable FXAA.

**Comment by Aikimaniak** [comment]
Guys,
Luke my new Hero!!!

I have found the fix, it was like looking after a mistake in a dictionary!!!
Please give me some credit if it worked for you too!!!

Open your open IV
And follow this path:

Mods
Update
Update.rpf
Common 
Data
Timecycle 

Then

Change this redux modified file by the original one :

timecycle_mods_1.xml

I have spend hours figuring out this trying everything to make the magic happened and I have finally sorted it out !!!

The game is just amazing the graphics looks gorgeous and Luke !!! Your mod is so F... crazy good!!!!
Best VR experience I had since the birth of VR!!!! I am a VR veteran...
(Oculus DK1- Htc vive - PSVR - Pimax 5K+ - Oculus Quest - Oculus Link - soon Pimax 8KX)

Have another trick that I saw nowhere else and that I am using !!! 

Sharing it with you guys:
Instead of playing with an Xbox controller like everyone else I found out a way to emulate one with 2 Sony nav controllers one in each hand... there is no tracking but it is already pure dope, believe me!!!
Used SCP Monitor and x360ce to make the magic happened.
Also tried mapping the Xbox 360 top shot elite but it wasn’t so great cause it misses one button and the Sony aim controller for VR that wasn’t so bad but not as convenient as the 2 nav cons...

With your mod on + my tricks + redux + Force feedback steering wheel + Hotas with rudders + motorbike controller (ps3) + yoke and rudder, the experience is just freaking amazing !!!

May I suggest one thing Luke?!?
If you manage to make the shake your head option OK for the Pimax you know it would be fantastic, do you think if it would be possible to make a keyboard hotkey to reset the VR view in game with your mod (not with the game I know it wouldn’t be impossible, but within your mod?) because this way we could either hit that button (ideally configurable one) or even better use voice attack to manage the reset : by using a voice command for exemple ... now it is impossible because the reset option in steam VR isn’t reachable by a keyboard hotkey but only by the VR controllers buttons press it once then wait 3 sec then you get the reset (boring...!)

So much to say ... sorry if I ve been invasive !!!

Cheers from France guys
Enjoy the tips!!!!!
Give some credit....
Love

**Comment by Aikimaniak** [comment]
Another little comment,
I know that redux is not your favorite Luke, it was the only one I tried (new to modding)...

But my feeling is that with redux on the Depth of view increased in a very significant way!!!
This gives even more sense to your mod!!!

Your mod gave us sight and redux put on us glasses (we were farsighted)

Before redux the game was already amazing in VR but somehow distant objects and buildings were foggy and blurred by the game itself I guess (maybe to save ressources) but with Redux on the image quality become so freaking good that you can see far away, like some kilometers away, with no problem, helicopters view on water up in the sky is so unbelievable!!!

Thank you Luke, I don’t know if you realize what you did with this mod but, I assure you you just made a master piece!!! You really should be famous!!!
