### ISSUE TITLE
friggin awesome where can donate?

### ISSUE THREAD

**Issue by rich0550** [LukeRoss00/gta5-real-mod#95]
also should 2160x2160 HP reverb need higher settings in the configurations?
how about Vive pro?

**Comment by LukeRoss00** [comment]
I'm not taking donations ATM, thanks anyway! The Vive Pro should work very well with the mod; the Reverb unfortunately not so much because Microsoft still needs to fix a couple of issues in their driver.

You could start with Medium settings and then if you have a very powerful PC try to push toward High
